# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\fault_properties.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(631, 564)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.prop_slickenline_ls = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_slickenline_ls.setObjectName("prop_slickenline_ls")
        self.prop_slickenline_ls.addItem("")
        self.prop_slickenline_ls.addItem("")
        self.prop_slickenline_ls.addItem("")
        self.prop_slickenline_ls.addItem("")
        self.gridLayout_4.addWidget(self.prop_slickenline_ls, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 2, 1, 1)
        self.prop_color_slickenline_arrowcolor = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_slickenline_arrowcolor.setText("")
        self.prop_color_slickenline_arrowcolor.setObjectName("prop_color_slickenline_arrowcolor")
        self.gridLayout_4.addWidget(self.prop_color_slickenline_arrowcolor, 1, 0, 1, 1)
        self.prop_slickenline_lw = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_slickenline_lw.setObjectName("prop_slickenline_lw")
        self.gridLayout_4.addWidget(self.prop_slickenline_lw, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.prop_check_m1point = QtWidgets.QCheckBox(self.groupBox_4)
        self.prop_check_m1point.setObjectName("prop_check_m1point")
        self.gridLayout_3.addWidget(self.prop_check_m1point, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.prop_m1point_marker = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_m1point_marker.setObjectName("prop_m1point_marker")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.prop_m1point_marker.addItem("")
        self.gridLayout_3.addWidget(self.prop_m1point_marker, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.prop_color_m1point_c = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_m1point_c.setText("")
        self.prop_color_m1point_c.setObjectName("prop_color_m1point_c")
        self.gridLayout_3.addWidget(self.prop_color_m1point_c, 1, 1, 1, 1)
        self.prop_m1point_ms = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_m1point_ms.setObjectName("prop_m1point_ms")
        self.gridLayout_3.addWidget(self.prop_m1point_ms, 1, 3, 1, 1)
        self.prop_color_m2point_c = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_m2point_c.setText("")
        self.prop_color_m2point_c.setObjectName("prop_color_m2point_c")
        self.gridLayout_3.addWidget(self.prop_color_m2point_c, 2, 1, 1, 1)
        self.prop_check_m2point = QtWidgets.QCheckBox(self.groupBox_4)
        self.prop_check_m2point.setObjectName("prop_check_m2point")
        self.gridLayout_3.addWidget(self.prop_check_m2point, 2, 0, 1, 1)
        self.prop_m2point_marker = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_m2point_marker.setObjectName("prop_m2point_marker")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.prop_m2point_marker.addItem("")
        self.gridLayout_3.addWidget(self.prop_m2point_marker, 2, 2, 1, 1)
        self.prop_check_m3point = QtWidgets.QCheckBox(self.groupBox_4)
        self.prop_check_m3point.setObjectName("prop_check_m3point")
        self.gridLayout_3.addWidget(self.prop_check_m3point, 3, 0, 1, 1)
        self.prop_m3point_marker = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_m3point_marker.setObjectName("prop_m3point_marker")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.prop_m3point_marker.addItem("")
        self.gridLayout_3.addWidget(self.prop_m3point_marker, 3, 2, 1, 1)
        self.prop_m2point_ms = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_m2point_ms.setObjectName("prop_m2point_ms")
        self.gridLayout_3.addWidget(self.prop_m2point_ms, 2, 3, 1, 1)
        self.prop_color_m3point_c = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_m3point_c.setText("")
        self.prop_color_m3point_c.setObjectName("prop_color_m3point_c")
        self.gridLayout_3.addWidget(self.prop_color_m3point_c, 3, 1, 1, 1)
        self.prop_m3point_ms = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_m3point_ms.setObjectName("prop_m3point_ms")
        self.gridLayout_3.addWidget(self.prop_m3point_ms, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.prop_color_slip_arrowcolor = QtWidgets.QPushButton(self.groupBox_2)
        self.prop_color_slip_arrowcolor.setText("")
        self.prop_color_slip_arrowcolor.setObjectName("prop_color_slip_arrowcolor")
        self.gridLayout_2.addWidget(self.prop_color_slip_arrowcolor, 1, 0, 1, 1)
        self.prop_slip_lw = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.prop_slip_lw.setObjectName("prop_slip_lw")
        self.gridLayout_2.addWidget(self.prop_slip_lw, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.prop_slip_ls = QtWidgets.QComboBox(self.groupBox_2)
        self.prop_slip_ls.setObjectName("prop_slip_ls")
        self.prop_slip_ls.addItem("")
        self.prop_slip_ls.addItem("")
        self.prop_slip_ls.addItem("")
        self.prop_slip_ls.addItem("")
        self.gridLayout_2.addWidget(self.prop_slip_ls, 1, 1, 1, 1)
        self.prop_slip_footwall = QtWidgets.QCheckBox(self.groupBox_2)
        self.prop_slip_footwall.setObjectName("prop_slip_footwall")
        self.gridLayout_2.addWidget(self.prop_slip_footwall, 2, 0, 1, 3)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.prop_contour_check_gradientline = QtWidgets.QRadioButton(self.groupBox_12)
        self.prop_contour_check_gradientline.setObjectName("prop_contour_check_gradientline")
        self.gridLayout_9.addWidget(self.prop_contour_check_gradientline, 3, 0, 1, 1)
        self.prop_contour_check_fillcontours = QtWidgets.QCheckBox(self.groupBox_12)
        self.prop_contour_check_fillcontours.setObjectName("prop_contour_check_fillcontours")
        self.gridLayout_9.addWidget(self.prop_contour_check_fillcontours, 4, 0, 1, 1)
        self.prop_contour_cmap = QtWidgets.QComboBox(self.groupBox_12)
        self.prop_contour_cmap.setObjectName("prop_contour_cmap")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.gridLayout_9.addWidget(self.prop_contour_cmap, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_12)
        self.label_30.setObjectName("label_30")
        self.gridLayout_9.addWidget(self.label_30, 0, 2, 1, 1)
        self.prop_contour_linestyles = QtWidgets.QComboBox(self.groupBox_12)
        self.prop_contour_linestyles.setObjectName("prop_contour_linestyles")
        self.prop_contour_linestyles.addItem("")
        self.prop_contour_linestyles.addItem("")
        self.prop_contour_linestyles.addItem("")
        self.prop_contour_linestyles.addItem("")
        self.gridLayout_9.addWidget(self.prop_contour_linestyles, 1, 1, 1, 1)
        self.prop_color_contour_line_colors = QtWidgets.QPushButton(self.groupBox_12)
        self.prop_color_contour_line_colors.setText("")
        self.prop_color_contour_line_colors.setObjectName("prop_color_contour_line_colors")
        self.gridLayout_9.addWidget(self.prop_color_contour_line_colors, 2, 1, 1, 1)
        self.prop_contour_line_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.prop_contour_line_linewidths.setObjectName("prop_contour_line_linewidths")
        self.gridLayout_9.addWidget(self.prop_contour_line_linewidths, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 0, 1, 1, 1)
        self.prop_contour_check_drawover = QtWidgets.QCheckBox(self.groupBox_12)
        self.prop_contour_check_drawover.setObjectName("prop_contour_check_drawover")
        self.gridLayout_9.addWidget(self.prop_contour_check_drawover, 1, 0, 1, 1)
        self.prop_contour_line_cmap = QtWidgets.QComboBox(self.groupBox_12)
        self.prop_contour_line_cmap.setObjectName("prop_contour_line_cmap")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.gridLayout_9.addWidget(self.prop_contour_line_cmap, 3, 1, 1, 1)
        self.prop_contour_check_solidline = QtWidgets.QRadioButton(self.groupBox_12)
        self.prop_contour_check_solidline.setObjectName("prop_contour_check_solidline")
        self.gridLayout_9.addWidget(self.prop_contour_check_solidline, 2, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_9)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_36 = QtWidgets.QLabel(self.groupBox_12)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_19.addWidget(self.label_36)
        self.prop_contour_cresolution = QtWidgets.QSpinBox(self.groupBox_12)
        self.prop_contour_cresolution.setMaximum(100000)
        self.prop_contour_cresolution.setObjectName("prop_contour_cresolution")
        self.horizontalLayout_19.addWidget(self.prop_contour_cresolution)
        self.prop_contour_antialiased = QtWidgets.QCheckBox(self.groupBox_12)
        self.prop_contour_antialiased.setObjectName("prop_contour_antialiased")
        self.horizontalLayout_19.addWidget(self.prop_contour_antialiased)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.gridLayout.addWidget(self.groupBox_12, 2, 0, 2, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout.setObjectName("formLayout")
        self.prop_checklegend_slickenlines = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_slickenlines.setObjectName("prop_checklegend_slickenlines")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_slickenlines)
        self.prop_legend_slickenlines = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_slickenlines.setObjectName("prop_legend_slickenlines")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prop_legend_slickenlines)
        self.prop_checklegend_slip = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_slip.setObjectName("prop_checklegend_slip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_slip)
        self.prop_legend_slip = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_slip.setObjectName("prop_legend_slip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prop_legend_slip)
        self.prop_checklegend_m1point = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_m1point.setObjectName("prop_checklegend_m1point")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_m1point)
        self.prop_legend_m1point = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_m1point.setObjectName("prop_legend_m1point")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prop_legend_m1point)
        self.prop_checklegend_m2point = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_m2point.setObjectName("prop_checklegend_m2point")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_m2point)
        self.prop_legend_m2point = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_m2point.setObjectName("prop_legend_m2point")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prop_legend_m2point)
        self.prop_checklegend_m3point = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_m3point.setObjectName("prop_checklegend_m3point")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_m3point)
        self.prop_legend_m3point = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_m3point.setObjectName("prop_legend_m3point")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.prop_legend_m3point)
        self.gridLayout.addWidget(self.groupBox_8, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.prop_data_sensecolumncheck = QtWidgets.QCheckBox(self.groupBox)
        self.prop_data_sensecolumncheck.setObjectName("prop_data_sensecolumncheck")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.prop_data_sensecolumncheck)
        self.prop_data_sensecolumn = QtWidgets.QSpinBox(self.groupBox)
        self.prop_data_sensecolumn.setObjectName("prop_data_sensecolumn")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prop_data_sensecolumn)
        self.prop_data_invertsense = QtWidgets.QCheckBox(self.groupBox)
        self.prop_data_invertsense.setObjectName("prop_data_invertsense")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prop_data_invertsense)
        self.verticalLayout.addLayout(self.formLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 2, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.prop_contour_check_minmax = QtWidgets.QRadioButton(self.groupBox_13)
        self.prop_contour_check_minmax.setObjectName("prop_contour_check_minmax")
        self.verticalLayout_12.addWidget(self.prop_contour_check_minmax)
        self.prop_contour_check_zeromax = QtWidgets.QRadioButton(self.groupBox_13)
        self.prop_contour_check_zeromax.setObjectName("prop_contour_check_zeromax")
        self.verticalLayout_12.addWidget(self.prop_contour_check_zeromax)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_31 = QtWidgets.QLabel(self.groupBox_13)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.prop_contour_ncontours = QtWidgets.QSpinBox(self.groupBox_13)
        self.prop_contour_ncontours.setObjectName("prop_contour_ncontours")
        self.horizontalLayout_17.addWidget(self.prop_contour_ncontours)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.prop_contour_check_customintervals = QtWidgets.QRadioButton(self.groupBox_13)
        self.prop_contour_check_customintervals.setObjectName("prop_contour_check_customintervals")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prop_contour_check_customintervals)
        self.prop_contour_intervals = QtWidgets.QLineEdit(self.groupBox_13)
        self.prop_contour_intervals.setObjectName("prop_contour_intervals")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prop_contour_intervals)
        self.verticalLayout_12.addLayout(self.formLayout_2)
        self.gridLayout.addWidget(self.groupBox_13, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.apply = QtWidgets.QPushButton(Dialog)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.ok_button.clicked.connect(Dialog.accept)
        self.cancel_button.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.prop_color_slickenline_arrowcolor, self.prop_slickenline_ls)
        Dialog.setTabOrder(self.prop_slickenline_ls, self.prop_slickenline_lw)
        Dialog.setTabOrder(self.prop_slickenline_lw, self.prop_color_slip_arrowcolor)
        Dialog.setTabOrder(self.prop_color_slip_arrowcolor, self.prop_slip_ls)
        Dialog.setTabOrder(self.prop_slip_ls, self.prop_slip_lw)
        Dialog.setTabOrder(self.prop_slip_lw, self.prop_slip_footwall)
        Dialog.setTabOrder(self.prop_slip_footwall, self.prop_contour_check_drawover)
        Dialog.setTabOrder(self.prop_contour_check_drawover, self.prop_contour_linestyles)
        Dialog.setTabOrder(self.prop_contour_linestyles, self.prop_contour_line_linewidths)
        Dialog.setTabOrder(self.prop_contour_line_linewidths, self.prop_contour_check_solidline)
        Dialog.setTabOrder(self.prop_contour_check_solidline, self.prop_color_contour_line_colors)
        Dialog.setTabOrder(self.prop_color_contour_line_colors, self.prop_contour_check_gradientline)
        Dialog.setTabOrder(self.prop_contour_check_gradientline, self.prop_contour_line_cmap)
        Dialog.setTabOrder(self.prop_contour_line_cmap, self.prop_contour_check_fillcontours)
        Dialog.setTabOrder(self.prop_contour_check_fillcontours, self.prop_contour_cmap)
        Dialog.setTabOrder(self.prop_contour_cmap, self.prop_contour_cresolution)
        Dialog.setTabOrder(self.prop_contour_cresolution, self.prop_contour_antialiased)
        Dialog.setTabOrder(self.prop_contour_antialiased, self.prop_contour_check_minmax)
        Dialog.setTabOrder(self.prop_contour_check_minmax, self.prop_contour_check_zeromax)
        Dialog.setTabOrder(self.prop_contour_check_zeromax, self.prop_contour_ncontours)
        Dialog.setTabOrder(self.prop_contour_ncontours, self.prop_contour_check_customintervals)
        Dialog.setTabOrder(self.prop_contour_check_customintervals, self.prop_contour_intervals)
        Dialog.setTabOrder(self.prop_contour_intervals, self.prop_checklegend_slickenlines)
        Dialog.setTabOrder(self.prop_checklegend_slickenlines, self.prop_legend_slickenlines)
        Dialog.setTabOrder(self.prop_legend_slickenlines, self.prop_checklegend_slip)
        Dialog.setTabOrder(self.prop_checklegend_slip, self.prop_legend_slip)
        Dialog.setTabOrder(self.prop_legend_slip, self.prop_checklegend_m1point)
        Dialog.setTabOrder(self.prop_checklegend_m1point, self.prop_legend_m1point)
        Dialog.setTabOrder(self.prop_legend_m1point, self.prop_checklegend_m2point)
        Dialog.setTabOrder(self.prop_checklegend_m2point, self.prop_legend_m2point)
        Dialog.setTabOrder(self.prop_legend_m2point, self.prop_checklegend_m3point)
        Dialog.setTabOrder(self.prop_checklegend_m3point, self.prop_legend_m3point)
        Dialog.setTabOrder(self.prop_legend_m3point, self.ok_button)
        Dialog.setTabOrder(self.ok_button, self.cancel_button)
        Dialog.setTabOrder(self.cancel_button, self.apply)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "Slickenlines"))
        self.prop_slickenline_ls.setItemText(0, _translate("Dialog", "-"))
        self.prop_slickenline_ls.setItemText(1, _translate("Dialog", ":"))
        self.prop_slickenline_ls.setItemText(2, _translate("Dialog", "--"))
        self.prop_slickenline_ls.setItemText(3, _translate("Dialog", "-."))
        self.label_16.setText(_translate("Dialog", "Symbol"))
        self.label_17.setText(_translate("Dialog", "Width"))
        self.label_18.setText(_translate("Dialog", "Color"))
        self.groupBox_4.setTitle(_translate("Dialog", "Michael Vectors"))
        self.prop_check_m1point.setText(_translate("Dialog", "Compressive"))
        self.label_8.setText(_translate("Dialog", "Size"))
        self.label_7.setText(_translate("Dialog", "Symbol"))
        self.prop_m1point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_m1point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_m1point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_m1point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_m1point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_m1point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_m1point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_m1point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_m1point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_m1point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_m1point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_m1point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_m1point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_m1point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_m1point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_m1point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_m1point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_m1point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_m1point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_m1point_marker.setItemText(19, _translate("Dialog", "4"))
        self.label_9.setText(_translate("Dialog", "Color"))
        self.prop_check_m2point.setText(_translate("Dialog", "Intermediate"))
        self.prop_m2point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_m2point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_m2point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_m2point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_m2point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_m2point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_m2point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_m2point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_m2point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_m2point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_m2point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_m2point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_m2point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_m2point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_m2point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_m2point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_m2point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_m2point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_m2point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_m2point_marker.setItemText(19, _translate("Dialog", "4"))
        self.prop_check_m3point.setText(_translate("Dialog", "Distensive"))
        self.prop_m3point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_m3point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_m3point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_m3point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_m3point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_m3point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_m3point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_m3point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_m3point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_m3point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_m3point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_m3point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_m3point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_m3point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_m3point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_m3point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_m3point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_m3point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_m3point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_m3point_marker.setItemText(19, _translate("Dialog", "4"))
        self.groupBox_2.setTitle(_translate("Dialog", "Slip"))
        self.label_4.setText(_translate("Dialog", "Symbol"))
        self.label_6.setText(_translate("Dialog", "Width"))
        self.label_5.setText(_translate("Dialog", "Color"))
        self.prop_slip_ls.setItemText(0, _translate("Dialog", "-"))
        self.prop_slip_ls.setItemText(1, _translate("Dialog", ":"))
        self.prop_slip_ls.setItemText(2, _translate("Dialog", "--"))
        self.prop_slip_ls.setItemText(3, _translate("Dialog", "-."))
        self.prop_slip_footwall.setText(_translate("Dialog", "Plot slip for footwall"))
        self.groupBox_12.setTitle(_translate("Dialog", "Graphic properties"))
        self.prop_contour_check_gradientline.setText(_translate("Dialog", "Gradient"))
        self.prop_contour_check_fillcontours.setText(_translate("Dialog", "Fill contours"))
        self.prop_contour_cmap.setItemText(0, _translate("Dialog", "jet"))
        self.prop_contour_cmap.setItemText(1, _translate("Dialog", "jet_r"))
        self.prop_contour_cmap.setItemText(2, _translate("Dialog", "hsv"))
        self.prop_contour_cmap.setItemText(3, _translate("Dialog", "hsv_r"))
        self.prop_contour_cmap.setItemText(4, _translate("Dialog", "Greys"))
        self.prop_contour_cmap.setItemText(5, _translate("Dialog", "Greys_r"))
        self.prop_contour_cmap.setItemText(6, _translate("Dialog", "Blues"))
        self.prop_contour_cmap.setItemText(7, _translate("Dialog", "Blues_r"))
        self.prop_contour_cmap.setItemText(8, _translate("Dialog", "Greens"))
        self.prop_contour_cmap.setItemText(9, _translate("Dialog", "Greens_r"))
        self.prop_contour_cmap.setItemText(10, _translate("Dialog", "Oranges"))
        self.prop_contour_cmap.setItemText(11, _translate("Dialog", "Oranges_r"))
        self.prop_contour_cmap.setItemText(12, _translate("Dialog", "Reds"))
        self.prop_contour_cmap.setItemText(13, _translate("Dialog", "Reds_r"))
        self.label_30.setText(_translate("Dialog", "Width"))
        self.prop_contour_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_contour_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_contour_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_contour_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_23.setText(_translate("Dialog", "Style"))
        self.prop_contour_check_drawover.setText(_translate("Dialog", "Contour Lines"))
        self.prop_contour_line_cmap.setItemText(0, _translate("Dialog", "jet"))
        self.prop_contour_line_cmap.setItemText(1, _translate("Dialog", "jet_r"))
        self.prop_contour_line_cmap.setItemText(2, _translate("Dialog", "hsv"))
        self.prop_contour_line_cmap.setItemText(3, _translate("Dialog", "hsv_r"))
        self.prop_contour_line_cmap.setItemText(4, _translate("Dialog", "Greys"))
        self.prop_contour_line_cmap.setItemText(5, _translate("Dialog", "Greys_r"))
        self.prop_contour_line_cmap.setItemText(6, _translate("Dialog", "Blues"))
        self.prop_contour_line_cmap.setItemText(7, _translate("Dialog", "Blues_r"))
        self.prop_contour_line_cmap.setItemText(8, _translate("Dialog", "Greens"))
        self.prop_contour_line_cmap.setItemText(9, _translate("Dialog", "Greens_r"))
        self.prop_contour_line_cmap.setItemText(10, _translate("Dialog", "Oranges"))
        self.prop_contour_line_cmap.setItemText(11, _translate("Dialog", "Oranges_r"))
        self.prop_contour_line_cmap.setItemText(12, _translate("Dialog", "Reds"))
        self.prop_contour_line_cmap.setItemText(13, _translate("Dialog", "Reds_r"))
        self.prop_contour_check_solidline.setText(_translate("Dialog", "Solid Color"))
        self.label_36.setText(_translate("Dialog", "Resolution"))
        self.prop_contour_antialiased.setText(_translate("Dialog", "Antialiased"))
        self.groupBox_8.setTitle(_translate("Dialog", "Data Legend"))
        self.prop_checklegend_slickenlines.setText(_translate("Dialog", "Slickenlines"))
        self.prop_checklegend_slip.setText(_translate("Dialog", "Slip"))
        self.prop_checklegend_m1point.setText(_translate("Dialog", "Michael Compressive"))
        self.prop_checklegend_m2point.setText(_translate("Dialog", "Michael Intermediate"))
        self.prop_checklegend_m3point.setText(_translate("Dialog", "Michael Distensive"))
        self.groupBox.setTitle(_translate("Dialog", "Data Settings"))
        self.prop_data_sensecolumncheck.setText(_translate("Dialog", "Sense Column"))
        self.prop_data_invertsense.setText(_translate("Dialog", "Invert Sense"))
        self.groupBox_13.setTitle(_translate("Dialog", "Contour Intervals"))
        self.prop_contour_check_minmax.setText(_translate("Dialog", "From minimum to maximum"))
        self.prop_contour_check_zeromax.setText(_translate("Dialog", "From zero to maximum"))
        self.label_31.setText(_translate("Dialog", "Number of contours"))
        self.prop_contour_check_customintervals.setText(_translate("Dialog", "Custom list"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.apply.setText(_translate("Dialog", "Apply"))

