# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\plane_properties.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 541)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.prop_color_point_c = QtWidgets.QPushButton(self.groupBox)
        self.prop_color_point_c.setText("")
        self.prop_color_point_c.setObjectName("prop_color_point_c")
        self.gridLayout.addWidget(self.prop_color_point_c, 1, 0, 1, 1)
        self.prop_point_marker = QtWidgets.QComboBox(self.groupBox)
        self.prop_point_marker.setObjectName("prop_point_marker")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.gridLayout.addWidget(self.prop_point_marker, 1, 1, 1, 1)
        self.prop_point_ms = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.prop_point_ms.setObjectName("prop_point_ms")
        self.gridLayout.addWidget(self.prop_point_ms, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.prop_color_GC_colors = QtWidgets.QPushButton(self.groupBox_2)
        self.prop_color_GC_colors.setText("")
        self.prop_color_GC_colors.setObjectName("prop_color_GC_colors")
        self.gridLayout_2.addWidget(self.prop_color_GC_colors, 1, 0, 1, 1)
        self.prop_GC_linestyles = QtWidgets.QComboBox(self.groupBox_2)
        self.prop_GC_linestyles.setObjectName("prop_GC_linestyles")
        self.prop_GC_linestyles.addItem("")
        self.prop_GC_linestyles.addItem("")
        self.prop_GC_linestyles.addItem("")
        self.prop_GC_linestyles.addItem("")
        self.gridLayout_2.addWidget(self.prop_GC_linestyles, 1, 1, 1, 1)
        self.prop_GC_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.prop_GC_linewidths.setObjectName("prop_GC_linewidths")
        self.gridLayout_2.addWidget(self.prop_GC_linewidths, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 2, 1, 1)
        self.prop_meanpoint_marker = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_meanpoint_marker.setObjectName("prop_meanpoint_marker")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.prop_meanpoint_marker.addItem("")
        self.gridLayout_4.addWidget(self.prop_meanpoint_marker, 1, 1, 1, 1)
        self.prop_meanpoint_ms = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_meanpoint_ms.setObjectName("prop_meanpoint_ms")
        self.gridLayout_4.addWidget(self.prop_meanpoint_ms, 1, 2, 1, 1)
        self.prop_color_meanpoint_c = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_meanpoint_c.setText("")
        self.prop_color_meanpoint_c.setObjectName("prop_color_meanpoint_c")
        self.gridLayout_4.addWidget(self.prop_color_meanpoint_c, 1, 0, 1, 1)
        self.prop_check_meanpoint = QtWidgets.QCheckBox(self.groupBox_4)
        self.prop_check_meanpoint.setObjectName("prop_check_meanpoint")
        self.gridLayout_4.addWidget(self.prop_check_meanpoint, 2, 0, 1, 1)
        self.prop_check_meanpointeiv = QtWidgets.QCheckBox(self.groupBox_4)
        self.prop_check_meanpointeiv.setObjectName("prop_check_meanpointeiv")
        self.gridLayout_4.addWidget(self.prop_check_meanpointeiv, 2, 1, 1, 2)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.gridLayout_20.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.prop_check_v1point = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_check_v1point.setObjectName("prop_check_v1point")
        self.gridLayout_3.addWidget(self.prop_check_v1point, 1, 0, 1, 1)
        self.prop_check_v1GC = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_check_v1GC.setObjectName("prop_check_v1GC")
        self.gridLayout_3.addWidget(self.prop_check_v1GC, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.prop_v1point_marker = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_v1point_marker.setObjectName("prop_v1point_marker")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.prop_v1point_marker.addItem("")
        self.gridLayout_3.addWidget(self.prop_v1point_marker, 1, 2, 1, 1)
        self.prop_color_v1point_c = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_v1point_c.setText("")
        self.prop_color_v1point_c.setObjectName("prop_color_v1point_c")
        self.gridLayout_3.addWidget(self.prop_color_v1point_c, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.prop_v1GC_linestyles = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_v1GC_linestyles.setObjectName("prop_v1GC_linestyles")
        self.prop_v1GC_linestyles.addItem("")
        self.prop_v1GC_linestyles.addItem("")
        self.prop_v1GC_linestyles.addItem("")
        self.prop_v1GC_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_v1GC_linestyles, 2, 2, 1, 1)
        self.prop_v1point_ms = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_v1point_ms.setObjectName("prop_v1point_ms")
        self.gridLayout_3.addWidget(self.prop_v1point_ms, 1, 3, 1, 1)
        self.prop_color_v1GC_colors = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_v1GC_colors.setText("")
        self.prop_color_v1GC_colors.setObjectName("prop_color_v1GC_colors")
        self.gridLayout_3.addWidget(self.prop_color_v1GC_colors, 2, 1, 1, 1)
        self.prop_color_v2point_c = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_v2point_c.setText("")
        self.prop_color_v2point_c.setObjectName("prop_color_v2point_c")
        self.gridLayout_3.addWidget(self.prop_color_v2point_c, 4, 1, 1, 1)
        self.prop_check_v2GC = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_check_v2GC.setObjectName("prop_check_v2GC")
        self.gridLayout_3.addWidget(self.prop_check_v2GC, 5, 0, 1, 1)
        self.prop_check_v2point = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_check_v2point.setObjectName("prop_check_v2point")
        self.gridLayout_3.addWidget(self.prop_check_v2point, 4, 0, 1, 1)
        self.prop_v1GC_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_v1GC_linewidths.setObjectName("prop_v1GC_linewidths")
        self.gridLayout_3.addWidget(self.prop_v1GC_linewidths, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.prop_v2point_marker = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_v2point_marker.setObjectName("prop_v2point_marker")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.prop_v2point_marker.addItem("")
        self.gridLayout_3.addWidget(self.prop_v2point_marker, 4, 2, 1, 1)
        self.prop_check_v3point = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_check_v3point.setObjectName("prop_check_v3point")
        self.gridLayout_3.addWidget(self.prop_check_v3point, 7, 0, 1, 1)
        self.prop_v3point_marker = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_v3point_marker.setObjectName("prop_v3point_marker")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.prop_v3point_marker.addItem("")
        self.gridLayout_3.addWidget(self.prop_v3point_marker, 7, 2, 1, 1)
        self.prop_color_v2GC_colors = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_v2GC_colors.setText("")
        self.prop_color_v2GC_colors.setObjectName("prop_color_v2GC_colors")
        self.gridLayout_3.addWidget(self.prop_color_v2GC_colors, 5, 1, 1, 1)
        self.prop_v2GC_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_v2GC_linewidths.setObjectName("prop_v2GC_linewidths")
        self.gridLayout_3.addWidget(self.prop_v2GC_linewidths, 5, 3, 1, 1)
        self.prop_v2point_ms = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_v2point_ms.setObjectName("prop_v2point_ms")
        self.gridLayout_3.addWidget(self.prop_v2point_ms, 4, 3, 1, 1)
        self.prop_check_v3GC = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_check_v3GC.setObjectName("prop_check_v3GC")
        self.gridLayout_3.addWidget(self.prop_check_v3GC, 8, 0, 1, 1)
        self.prop_color_v3point_c = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_v3point_c.setText("")
        self.prop_color_v3point_c.setObjectName("prop_color_v3point_c")
        self.gridLayout_3.addWidget(self.prop_color_v3point_c, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 1)
        self.prop_v2GC_linestyles = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_v2GC_linestyles.setObjectName("prop_v2GC_linestyles")
        self.prop_v2GC_linestyles.addItem("")
        self.prop_v2GC_linestyles.addItem("")
        self.prop_v2GC_linestyles.addItem("")
        self.prop_v2GC_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_v2GC_linestyles, 5, 2, 1, 1)
        self.prop_v3GC_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_v3GC_linewidths.setObjectName("prop_v3GC_linewidths")
        self.gridLayout_3.addWidget(self.prop_v3GC_linewidths, 8, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.prop_v3GC_linestyles = QtWidgets.QComboBox(self.groupBox_3)
        self.prop_v3GC_linestyles.setObjectName("prop_v3GC_linestyles")
        self.prop_v3GC_linestyles.addItem("")
        self.prop_v3GC_linestyles.addItem("")
        self.prop_v3GC_linestyles.addItem("")
        self.prop_v3GC_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_v3GC_linestyles, 8, 2, 1, 1)
        self.prop_v3point_ms = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.prop_v3point_ms.setObjectName("prop_v3point_ms")
        self.gridLayout_3.addWidget(self.prop_v3point_ms, 7, 3, 1, 1)
        self.prop_color_v3GC_colors = QtWidgets.QPushButton(self.groupBox_3)
        self.prop_color_v3GC_colors.setText("")
        self.prop_color_v3GC_colors.setObjectName("prop_color_v3GC_colors")
        self.gridLayout_3.addWidget(self.prop_color_v3GC_colors, 8, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.gridLayout_20.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_41 = QtWidgets.QLabel(self.groupBox_11)
        self.label_41.setObjectName("label_41")
        self.gridLayout_19.addWidget(self.label_41, 0, 1, 1, 1)
        self.prop_check_scaxis = QtWidgets.QCheckBox(self.groupBox_11)
        self.prop_check_scaxis.setObjectName("prop_check_scaxis")
        self.gridLayout_19.addWidget(self.prop_check_scaxis, 1, 0, 1, 1)
        self.prop_color_scaxis_c = QtWidgets.QPushButton(self.groupBox_11)
        self.prop_color_scaxis_c.setText("")
        self.prop_color_scaxis_c.setObjectName("prop_color_scaxis_c")
        self.gridLayout_19.addWidget(self.prop_color_scaxis_c, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setObjectName("label_40")
        self.gridLayout_19.addWidget(self.label_40, 0, 2, 1, 1)
        self.prop_scaxis_marker = QtWidgets.QComboBox(self.groupBox_11)
        self.prop_scaxis_marker.setObjectName("prop_scaxis_marker")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.gridLayout_19.addWidget(self.prop_scaxis_marker, 1, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_11)
        self.label_43.setObjectName("label_43")
        self.gridLayout_19.addWidget(self.label_43, 0, 3, 1, 1)
        self.prop_scaxis_ms = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.prop_scaxis_ms.setObjectName("prop_scaxis_ms")
        self.gridLayout_19.addWidget(self.prop_scaxis_ms, 1, 3, 1, 1)
        self.prop_sccirc_linestyles = QtWidgets.QComboBox(self.groupBox_11)
        self.prop_sccirc_linestyles.setObjectName("prop_sccirc_linestyles")
        self.prop_sccirc_linestyles.addItem("")
        self.prop_sccirc_linestyles.addItem("")
        self.prop_sccirc_linestyles.addItem("")
        self.prop_sccirc_linestyles.addItem("")
        self.gridLayout_19.addWidget(self.prop_sccirc_linestyles, 2, 2, 1, 1)
        self.prop_check_sccirc = QtWidgets.QCheckBox(self.groupBox_11)
        self.prop_check_sccirc.setObjectName("prop_check_sccirc")
        self.gridLayout_19.addWidget(self.prop_check_sccirc, 2, 0, 1, 1)
        self.prop_sccirc_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.prop_sccirc_linewidths.setObjectName("prop_sccirc_linewidths")
        self.gridLayout_19.addWidget(self.prop_sccirc_linewidths, 2, 3, 1, 1)
        self.prop_color_sccirc_colors = QtWidgets.QPushButton(self.groupBox_11)
        self.prop_color_sccirc_colors.setText("")
        self.prop_color_sccirc_colors.setObjectName("prop_color_sccirc_colors")
        self.gridLayout_19.addWidget(self.prop_color_sccirc_colors, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_19)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.prop_check_concentratesc = QtWidgets.QCheckBox(self.groupBox_11)
        self.prop_check_concentratesc.setObjectName("prop_check_concentratesc")
        self.horizontalLayout_14.addWidget(self.prop_check_concentratesc)
        self.prop_sccalc_eiv = QtWidgets.QSpinBox(self.groupBox_11)
        self.prop_sccalc_eiv.setObjectName("prop_sccalc_eiv")
        self.horizontalLayout_14.addWidget(self.prop_sccalc_eiv)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.prop_data_smallcircle = QtWidgets.QLineEdit(self.groupBox_11)
        self.prop_data_smallcircle.setObjectName("prop_data_smallcircle")
        self.verticalLayout_7.addWidget(self.prop_data_smallcircle)
        self.gridLayout_20.addWidget(self.groupBox_11, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.prop_contour_check_gradientline = QtWidgets.QRadioButton(self.groupBox_12)
        self.prop_contour_check_gradientline.setObjectName("prop_contour_check_gradientline")
        self.gridLayout_9.addWidget(self.prop_contour_check_gradientline, 3, 0, 1, 1)
        self.prop_contour_check_fillcontours = QtWidgets.QCheckBox(self.groupBox_12)
        self.prop_contour_check_fillcontours.setObjectName("prop_contour_check_fillcontours")
        self.gridLayout_9.addWidget(self.prop_contour_check_fillcontours, 4, 0, 1, 1)
        self.prop_contour_cmap = QtWidgets.QComboBox(self.groupBox_12)
        self.prop_contour_cmap.setObjectName("prop_contour_cmap")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.prop_contour_cmap.addItem("")
        self.gridLayout_9.addWidget(self.prop_contour_cmap, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_12)
        self.label_30.setObjectName("label_30")
        self.gridLayout_9.addWidget(self.label_30, 0, 2, 1, 1)
        self.prop_contour_linestyles = QtWidgets.QComboBox(self.groupBox_12)
        self.prop_contour_linestyles.setObjectName("prop_contour_linestyles")
        self.prop_contour_linestyles.addItem("")
        self.prop_contour_linestyles.addItem("")
        self.prop_contour_linestyles.addItem("")
        self.prop_contour_linestyles.addItem("")
        self.gridLayout_9.addWidget(self.prop_contour_linestyles, 1, 1, 1, 1)
        self.prop_color_contour_line_colors = QtWidgets.QPushButton(self.groupBox_12)
        self.prop_color_contour_line_colors.setText("")
        self.prop_color_contour_line_colors.setObjectName("prop_color_contour_line_colors")
        self.gridLayout_9.addWidget(self.prop_color_contour_line_colors, 2, 1, 1, 1)
        self.prop_contour_line_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.prop_contour_line_linewidths.setObjectName("prop_contour_line_linewidths")
        self.gridLayout_9.addWidget(self.prop_contour_line_linewidths, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 0, 1, 1, 1)
        self.prop_contour_check_drawover = QtWidgets.QCheckBox(self.groupBox_12)
        self.prop_contour_check_drawover.setObjectName("prop_contour_check_drawover")
        self.gridLayout_9.addWidget(self.prop_contour_check_drawover, 1, 0, 1, 1)
        self.prop_contour_line_cmap = QtWidgets.QComboBox(self.groupBox_12)
        self.prop_contour_line_cmap.setObjectName("prop_contour_line_cmap")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.prop_contour_line_cmap.addItem("")
        self.gridLayout_9.addWidget(self.prop_contour_line_cmap, 3, 1, 1, 1)
        self.prop_contour_check_solidline = QtWidgets.QRadioButton(self.groupBox_12)
        self.prop_contour_check_solidline.setObjectName("prop_contour_check_solidline")
        self.gridLayout_9.addWidget(self.prop_contour_check_solidline, 2, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_9)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_36 = QtWidgets.QLabel(self.groupBox_12)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_19.addWidget(self.label_36)
        self.prop_contour_cresolution = QtWidgets.QSpinBox(self.groupBox_12)
        self.prop_contour_cresolution.setMaximum(100000)
        self.prop_contour_cresolution.setObjectName("prop_contour_cresolution")
        self.horizontalLayout_19.addWidget(self.prop_contour_cresolution)
        self.prop_contour_antialiased = QtWidgets.QCheckBox(self.groupBox_12)
        self.prop_contour_antialiased.setObjectName("prop_contour_antialiased")
        self.horizontalLayout_19.addWidget(self.prop_contour_antialiased)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.verticalLayout_13.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.prop_contour_check_minmax = QtWidgets.QRadioButton(self.groupBox_13)
        self.prop_contour_check_minmax.setObjectName("prop_contour_check_minmax")
        self.verticalLayout_12.addWidget(self.prop_contour_check_minmax)
        self.prop_contour_check_zeromax = QtWidgets.QRadioButton(self.groupBox_13)
        self.prop_contour_check_zeromax.setObjectName("prop_contour_check_zeromax")
        self.verticalLayout_12.addWidget(self.prop_contour_check_zeromax)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_31 = QtWidgets.QLabel(self.groupBox_13)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.prop_contour_ncontours = QtWidgets.QSpinBox(self.groupBox_13)
        self.prop_contour_ncontours.setObjectName("prop_contour_ncontours")
        self.horizontalLayout_17.addWidget(self.prop_contour_ncontours)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.prop_contour_check_customintervals = QtWidgets.QRadioButton(self.groupBox_13)
        self.prop_contour_check_customintervals.setObjectName("prop_contour_check_customintervals")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prop_contour_check_customintervals)
        self.prop_contour_intervals = QtWidgets.QLineEdit(self.groupBox_13)
        self.prop_contour_intervals.setObjectName("prop_contour_intervals")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prop_contour_intervals)
        self.verticalLayout_12.addLayout(self.formLayout)
        self.verticalLayout_13.addWidget(self.groupBox_13)
        spacerItem3 = QtWidgets.QSpacerItem(14, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_32 = QtWidgets.QLabel(self.groupBox_14)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        self.prop_contour_calc_spacing = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.prop_contour_calc_spacing.setObjectName("prop_contour_calc_spacing")
        self.horizontalLayout_18.addWidget(self.prop_contour_calc_spacing)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.prop_contour_check_fisher = QtWidgets.QRadioButton(self.groupBox_14)
        self.prop_contour_check_fisher.setObjectName("prop_contour_check_fisher")
        self.gridLayout_10.addWidget(self.prop_contour_check_fisher, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_14)
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 0, 1, 1, 1)
        self.prop_contour_calc_K = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.prop_contour_calc_K.setMaximum(10000.0)
        self.prop_contour_calc_K.setObjectName("prop_contour_calc_K")
        self.gridLayout_10.addWidget(self.prop_contour_calc_K, 0, 2, 1, 1)
        self.prop_contour_check_scperc = QtWidgets.QRadioButton(self.groupBox_14)
        self.prop_contour_check_scperc.setObjectName("prop_contour_check_scperc")
        self.gridLayout_10.addWidget(self.prop_contour_check_scperc, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_14)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 1, 1, 1, 1)
        self.prop_contour_calc_scperc = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.prop_contour_calc_scperc.setMaximum(100.0)
        self.prop_contour_calc_scperc.setObjectName("prop_contour_calc_scperc")
        self.gridLayout_10.addWidget(self.prop_contour_calc_scperc, 1, 2, 2, 1)
        self.prop_contour_check_scangle = QtWidgets.QRadioButton(self.groupBox_14)
        self.prop_contour_check_scangle.setObjectName("prop_contour_check_scangle")
        self.gridLayout_10.addWidget(self.prop_contour_check_scangle, 2, 0, 2, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_14)
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 3, 1, 1, 1)
        self.prop_contour_calc_scangle = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.prop_contour_calc_scangle.setMaximum(90.0)
        self.prop_contour_calc_scangle.setObjectName("prop_contour_calc_scangle")
        self.gridLayout_10.addWidget(self.prop_contour_calc_scangle, 3, 2, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_10)
        self.prop_contour_check_autocount = QtWidgets.QCheckBox(self.groupBox_14)
        self.prop_contour_check_autocount.setObjectName("prop_contour_check_autocount")
        self.verticalLayout_14.addWidget(self.prop_contour_check_autocount)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.prop_contour_check_robinjowett = QtWidgets.QRadioButton(self.groupBox_15)
        self.prop_contour_check_robinjowett.setObjectName("prop_contour_check_robinjowett")
        self.verticalLayout_15.addWidget(self.prop_contour_check_robinjowett)
        self.prop_contour_check_digglefisher = QtWidgets.QRadioButton(self.groupBox_15)
        self.prop_contour_check_digglefisher.setObjectName("prop_contour_check_digglefisher")
        self.verticalLayout_15.addWidget(self.prop_contour_check_digglefisher)
        self.verticalLayout_14.addWidget(self.groupBox_15)
        self.verticalLayout_10.addWidget(self.groupBox_14)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_2, "")
        self.roseDiagram = QtWidgets.QWidget()
        self.roseDiagram.setObjectName("roseDiagram")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.roseDiagram)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_9 = QtWidgets.QGroupBox(self.roseDiagram)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 0, 2, 1, 1)
        self.prop_rose_mean_linewidth = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.prop_rose_mean_linewidth.setObjectName("prop_rose_mean_linewidth")
        self.gridLayout_7.addWidget(self.prop_rose_mean_linewidth, 1, 3, 1, 1)
        self.prop_color_rose_mean_color = QtWidgets.QPushButton(self.groupBox_9)
        self.prop_color_rose_mean_color.setText("")
        self.prop_color_rose_mean_color.setObjectName("prop_color_rose_mean_color")
        self.gridLayout_7.addWidget(self.prop_color_rose_mean_color, 1, 2, 1, 1)
        self.prop_rose_check_mean = QtWidgets.QCheckBox(self.groupBox_9)
        self.prop_rose_check_mean.setObjectName("prop_rose_check_mean")
        self.gridLayout_7.addWidget(self.prop_rose_check_mean, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 0, 3, 1, 1)
        self.prop_rose_mean_linestyle = QtWidgets.QComboBox(self.groupBox_9)
        self.prop_rose_mean_linestyle.setObjectName("prop_rose_mean_linestyle")
        self.prop_rose_mean_linestyle.addItem("")
        self.prop_rose_mean_linestyle.addItem("")
        self.prop_rose_mean_linestyle.addItem("")
        self.prop_rose_mean_linestyle.addItem("")
        self.gridLayout_7.addWidget(self.prop_rose_mean_linestyle, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_9)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 1, 1, 1)
        self.prop_rose_check_confidence = QtWidgets.QCheckBox(self.groupBox_9)
        self.prop_rose_check_confidence.setObjectName("prop_rose_check_confidence")
        self.gridLayout_7.addWidget(self.prop_rose_check_confidence, 2, 1, 1, 2)
        self.prop_rose_confidence = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.prop_rose_confidence.setMaximum(100.0)
        self.prop_rose_confidence.setObjectName("prop_rose_confidence")
        self.gridLayout_7.addWidget(self.prop_rose_confidence, 2, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.gridLayout_6.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.roseDiagram)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.prop_rose_check_360d = QtWidgets.QRadioButton(self.groupBox_6)
        self.prop_rose_check_360d.setObjectName("prop_rose_check_360d")
        self.verticalLayout_4.addWidget(self.prop_rose_check_360d)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.prop_rose_check_180d = QtWidgets.QRadioButton(self.groupBox_6)
        self.prop_rose_check_180d.setObjectName("prop_rose_check_180d")
        self.horizontalLayout_13.addWidget(self.prop_rose_check_180d)
        self.prop_rose_180half = QtWidgets.QComboBox(self.groupBox_6)
        self.prop_rose_180half.setObjectName("prop_rose_180half")
        self.prop_rose_180half.addItem("")
        self.prop_rose_180half.addItem("")
        self.horizontalLayout_13.addWidget(self.prop_rose_180half)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.prop_rose_check_interval = QtWidgets.QRadioButton(self.groupBox_6)
        self.prop_rose_check_interval.setObjectName("prop_rose_check_interval")
        self.horizontalLayout_9.addWidget(self.prop_rose_check_interval)
        self.prop_rose_intervalfrom = QtWidgets.QSpinBox(self.groupBox_6)
        self.prop_rose_intervalfrom.setMinimum(-360)
        self.prop_rose_intervalfrom.setMaximum(360)
        self.prop_rose_intervalfrom.setObjectName("prop_rose_intervalfrom")
        self.horizontalLayout_9.addWidget(self.prop_rose_intervalfrom)
        self.prop_rose_intervalto = QtWidgets.QSpinBox(self.groupBox_6)
        self.prop_rose_intervalto.setMinimum(-360)
        self.prop_rose_intervalto.setMaximum(360)
        self.prop_rose_intervalto.setObjectName("prop_rose_intervalto")
        self.horizontalLayout_9.addWidget(self.prop_rose_intervalto)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout_6.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.roseDiagram)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.prop_rose_check_standard = QtWidgets.QRadioButton(self.groupBox_16)
        self.prop_rose_check_standard.setObjectName("prop_rose_check_standard")
        self.gridLayout_5.addWidget(self.prop_rose_check_standard, 0, 0, 1, 1)
        self.prop_rose_binwidth = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.prop_rose_binwidth.setMaximum(360.0)
        self.prop_rose_binwidth.setObjectName("prop_rose_binwidth")
        self.gridLayout_5.addWidget(self.prop_rose_binwidth, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_16)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 1, 1, 1)
        self.prop_rose_offset = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.prop_rose_offset.setMinimum(-360.0)
        self.prop_rose_offset.setMaximum(360.0)
        self.prop_rose_offset.setObjectName("prop_rose_offset")
        self.gridLayout_5.addWidget(self.prop_rose_offset, 0, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_16)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_16)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 1, 1, 1)
        self.prop_rose_check_continuous = QtWidgets.QRadioButton(self.groupBox_16)
        self.prop_rose_check_continuous.setObjectName("prop_rose_check_continuous")
        self.gridLayout_5.addWidget(self.prop_rose_check_continuous, 1, 0, 1, 1)
        self.prop_rose_aperture = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.prop_rose_aperture.setMaximum(360.0)
        self.prop_rose_aperture.setObjectName("prop_rose_aperture")
        self.gridLayout_5.addWidget(self.prop_rose_aperture, 1, 2, 1, 1)
        self.prop_rose_weightmunro = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.prop_rose_weightmunro.setMaximum(1.0)
        self.prop_rose_weightmunro.setSingleStep(0.01)
        self.prop_rose_weightmunro.setObjectName("prop_rose_weightmunro")
        self.gridLayout_5.addWidget(self.prop_rose_weightmunro, 1, 4, 1, 1)
        self.prop_rose_check_weightmunro = QtWidgets.QCheckBox(self.groupBox_16)
        self.prop_rose_check_weightmunro.setObjectName("prop_rose_check_weightmunro")
        self.gridLayout_5.addWidget(self.prop_rose_check_weightmunro, 1, 3, 1, 1)
        self.prop_rose_spacing = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.prop_rose_spacing.setMaximum(360.0)
        self.prop_rose_spacing.setObjectName("prop_rose_spacing")
        self.gridLayout_5.addWidget(self.prop_rose_spacing, 2, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_16)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_16)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 2, 3, 1, 1)
        self.prop_rose_offsetcont = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.prop_rose_offsetcont.setMinimum(-360.0)
        self.prop_rose_offsetcont.setMaximum(360.0)
        self.prop_rose_offsetcont.setObjectName("prop_rose_offsetcont")
        self.gridLayout_5.addWidget(self.prop_rose_offsetcont, 2, 4, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.roseDiagram)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.prop_rose_check_petalsfill = QtWidgets.QCheckBox(self.groupBox_7)
        self.prop_rose_check_petalsfill.setObjectName("prop_rose_check_petalsfill")
        self.gridLayout_8.addWidget(self.prop_rose_check_petalsfill, 0, 1, 1, 1)
        self.prop_rose_check_petalsoutline = QtWidgets.QCheckBox(self.groupBox_7)
        self.prop_rose_check_petalsoutline.setObjectName("prop_rose_check_petalsoutline")
        self.gridLayout_8.addWidget(self.prop_rose_check_petalsoutline, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 3, 1, 1)
        self.prop_rose_check_petals = QtWidgets.QRadioButton(self.groupBox_7)
        self.prop_rose_check_petals.setObjectName("prop_rose_check_petals")
        self.gridLayout_8.addWidget(self.prop_rose_check_petals, 1, 0, 1, 1)
        self.prop_color_petals_facecolor = QtWidgets.QPushButton(self.groupBox_7)
        self.prop_color_petals_facecolor.setText("")
        self.prop_color_petals_facecolor.setObjectName("prop_color_petals_facecolor")
        self.gridLayout_8.addWidget(self.prop_color_petals_facecolor, 1, 1, 1, 1)
        self.prop_color_petals_edgecolor = QtWidgets.QPushButton(self.groupBox_7)
        self.prop_color_petals_edgecolor.setText("")
        self.prop_color_petals_edgecolor.setObjectName("prop_color_petals_edgecolor")
        self.gridLayout_8.addWidget(self.prop_color_petals_edgecolor, 1, 2, 1, 1)
        self.prop_petals_linewidth = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.prop_petals_linewidth.setObjectName("prop_petals_linewidth")
        self.gridLayout_8.addWidget(self.prop_petals_linewidth, 1, 3, 1, 1)
        self.prop_rose_check_kitefill = QtWidgets.QCheckBox(self.groupBox_7)
        self.prop_rose_check_kitefill.setObjectName("prop_rose_check_kitefill")
        self.gridLayout_8.addWidget(self.prop_rose_check_kitefill, 2, 1, 1, 1)
        self.prop_rose_check_kiteoutline = QtWidgets.QCheckBox(self.groupBox_7)
        self.prop_rose_check_kiteoutline.setObjectName("prop_rose_check_kiteoutline")
        self.gridLayout_8.addWidget(self.prop_rose_check_kiteoutline, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 2, 3, 1, 1)
        self.prop_rose_check_kite = QtWidgets.QRadioButton(self.groupBox_7)
        self.prop_rose_check_kite.setObjectName("prop_rose_check_kite")
        self.gridLayout_8.addWidget(self.prop_rose_check_kite, 3, 0, 1, 1)
        self.prop_color_kite_facecolor = QtWidgets.QPushButton(self.groupBox_7)
        self.prop_color_kite_facecolor.setText("")
        self.prop_color_kite_facecolor.setObjectName("prop_color_kite_facecolor")
        self.gridLayout_8.addWidget(self.prop_color_kite_facecolor, 3, 1, 1, 1)
        self.prop_color_kite_edgecolor = QtWidgets.QPushButton(self.groupBox_7)
        self.prop_color_kite_edgecolor.setText("")
        self.prop_color_kite_edgecolor.setObjectName("prop_color_kite_edgecolor")
        self.gridLayout_8.addWidget(self.prop_color_kite_edgecolor, 3, 2, 1, 1)
        self.prop_kite_linewidth = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.prop_kite_linewidth.setObjectName("prop_kite_linewidth")
        self.gridLayout_8.addWidget(self.prop_kite_linewidth, 3, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 4, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 4, 3, 1, 1)
        self.prop_rose_check_lines = QtWidgets.QRadioButton(self.groupBox_7)
        self.prop_rose_check_lines.setObjectName("prop_rose_check_lines")
        self.gridLayout_8.addWidget(self.prop_rose_check_lines, 5, 0, 1, 1)
        self.prop_lines_linestyle = QtWidgets.QComboBox(self.groupBox_7)
        self.prop_lines_linestyle.setObjectName("prop_lines_linestyle")
        self.prop_lines_linestyle.addItem("")
        self.prop_lines_linestyle.addItem("")
        self.prop_lines_linestyle.addItem("")
        self.prop_lines_linestyle.addItem("")
        self.gridLayout_8.addWidget(self.prop_lines_linestyle, 5, 1, 1, 1)
        self.prop_color_lines_color = QtWidgets.QPushButton(self.groupBox_7)
        self.prop_color_lines_color.setText("")
        self.prop_color_lines_color.setObjectName("prop_color_lines_color")
        self.gridLayout_8.addWidget(self.prop_color_lines_color, 5, 2, 1, 1)
        self.prop_lines_linewidth = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.prop_lines_linewidth.setObjectName("prop_lines_linewidth")
        self.gridLayout_8.addWidget(self.prop_lines_linewidth, 5, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.prop_rose_check_meandeviation = QtWidgets.QCheckBox(self.groupBox_7)
        self.prop_rose_check_meandeviation.setObjectName("prop_rose_check_meandeviation")
        self.horizontalLayout_11.addWidget(self.prop_rose_check_meandeviation)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.gridLayout_6.addWidget(self.groupBox_7, 0, 1, 2, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.roseDiagram)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.prop_rose_check_dd = QtWidgets.QRadioButton(self.groupBox_5)
        self.prop_rose_check_dd.setObjectName("prop_rose_check_dd")
        self.verticalLayout_3.addWidget(self.prop_rose_check_dd)
        self.prop_rose_check_dir = QtWidgets.QRadioButton(self.groupBox_5)
        self.prop_rose_check_dir.setObjectName("prop_rose_check_dir")
        self.verticalLayout_3.addWidget(self.prop_rose_check_dir)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.prop_rose_check_diraxial = QtWidgets.QCheckBox(self.groupBox_5)
        self.prop_rose_check_diraxial.setObjectName("prop_rose_check_diraxial")
        self.horizontalLayout_10.addWidget(self.prop_rose_check_diraxial)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.prop_rose_check_weightcolumn = QtWidgets.QCheckBox(self.groupBox_5)
        self.prop_rose_check_weightcolumn.setObjectName("prop_rose_check_weightcolumn")
        self.horizontalLayout_10.addWidget(self.prop_rose_check_weightcolumn)
        self.prop_rose_weightcolumn = QtWidgets.QSpinBox(self.groupBox_5)
        self.prop_rose_weightcolumn.setMaximum(16384)
        self.prop_rose_weightcolumn.setObjectName("prop_rose_weightcolumn")
        self.horizontalLayout_10.addWidget(self.prop_rose_weightcolumn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout_6.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.tabWidget.addTab(self.roseDiagram, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.show_auttitude_data_statistics = QtWidgets.QTextEdit(self.tab_3)
        self.show_auttitude_data_statistics.setObjectName("show_auttitude_data_statistics")
        self.horizontalLayout_6.addWidget(self.show_auttitude_data_statistics)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.prop_legend_point = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_point.setObjectName("prop_legend_point")
        self.gridLayout_11.addWidget(self.prop_legend_point, 0, 1, 1, 1)
        self.prop_checklegend_GC = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_GC.setObjectName("prop_checklegend_GC")
        self.gridLayout_11.addWidget(self.prop_checklegend_GC, 1, 0, 1, 1)
        self.prop_legend_GC = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_GC.setObjectName("prop_legend_GC")
        self.gridLayout_11.addWidget(self.prop_legend_GC, 1, 1, 1, 1)
        self.prop_checklegend_point = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_point.setObjectName("prop_checklegend_point")
        self.gridLayout_11.addWidget(self.prop_checklegend_point, 0, 0, 1, 1)
        self.prop_checklegend_meanpoint = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_meanpoint.setObjectName("prop_checklegend_meanpoint")
        self.gridLayout_11.addWidget(self.prop_checklegend_meanpoint, 2, 0, 1, 1)
        self.prop_legend_meanpoint = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_meanpoint.setObjectName("prop_legend_meanpoint")
        self.gridLayout_11.addWidget(self.prop_legend_meanpoint, 2, 1, 1, 1)
        self.verticalLayout_19.addWidget(self.groupBox_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setObjectName("label_16")
        self.gridLayout_16.addWidget(self.label_16, 0, 0, 1, 1)
        self.prop_checklegend_v1point = QtWidgets.QCheckBox(self.groupBox_10)
        self.prop_checklegend_v1point.setObjectName("prop_checklegend_v1point")
        self.gridLayout_16.addWidget(self.prop_checklegend_v1point, 1, 0, 1, 1)
        self.prop_legend_v1point = QtWidgets.QLineEdit(self.groupBox_10)
        self.prop_legend_v1point.setObjectName("prop_legend_v1point")
        self.gridLayout_16.addWidget(self.prop_legend_v1point, 1, 1, 1, 1)
        self.prop_checklegend_v1GC = QtWidgets.QCheckBox(self.groupBox_10)
        self.prop_checklegend_v1GC.setObjectName("prop_checklegend_v1GC")
        self.gridLayout_16.addWidget(self.prop_checklegend_v1GC, 2, 0, 1, 1)
        self.prop_legend_v1GC = QtWidgets.QLineEdit(self.groupBox_10)
        self.prop_legend_v1GC.setObjectName("prop_legend_v1GC")
        self.gridLayout_16.addWidget(self.prop_legend_v1GC, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 3, 0, 1, 1)
        self.prop_checklegend_v2point = QtWidgets.QCheckBox(self.groupBox_10)
        self.prop_checklegend_v2point.setObjectName("prop_checklegend_v2point")
        self.gridLayout_16.addWidget(self.prop_checklegend_v2point, 4, 0, 1, 1)
        self.prop_legend_v2point = QtWidgets.QLineEdit(self.groupBox_10)
        self.prop_legend_v2point.setObjectName("prop_legend_v2point")
        self.gridLayout_16.addWidget(self.prop_legend_v2point, 4, 1, 1, 1)
        self.prop_checklegend_v2GC = QtWidgets.QCheckBox(self.groupBox_10)
        self.prop_checklegend_v2GC.setObjectName("prop_checklegend_v2GC")
        self.gridLayout_16.addWidget(self.prop_checklegend_v2GC, 5, 0, 1, 1)
        self.prop_legend_v2GC = QtWidgets.QLineEdit(self.groupBox_10)
        self.prop_legend_v2GC.setObjectName("prop_legend_v2GC")
        self.gridLayout_16.addWidget(self.prop_legend_v2GC, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setObjectName("label_21")
        self.gridLayout_16.addWidget(self.label_21, 6, 0, 1, 1)
        self.prop_checklegend_v3point = QtWidgets.QCheckBox(self.groupBox_10)
        self.prop_checklegend_v3point.setObjectName("prop_checklegend_v3point")
        self.gridLayout_16.addWidget(self.prop_checklegend_v3point, 7, 0, 1, 1)
        self.prop_legend_v3point = QtWidgets.QLineEdit(self.groupBox_10)
        self.prop_legend_v3point.setObjectName("prop_legend_v3point")
        self.gridLayout_16.addWidget(self.prop_legend_v3point, 7, 1, 1, 1)
        self.prop_checklegend_v3GC = QtWidgets.QCheckBox(self.groupBox_10)
        self.prop_checklegend_v3GC.setObjectName("prop_checklegend_v3GC")
        self.gridLayout_16.addWidget(self.prop_checklegend_v3GC, 8, 0, 1, 1)
        self.prop_legend_v3GC = QtWidgets.QLineEdit(self.groupBox_10)
        self.prop_legend_v3GC.setObjectName("prop_legend_v3GC")
        self.gridLayout_16.addWidget(self.prop_legend_v3GC, 8, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_10)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.prop_checklegend_scaxis = QtWidgets.QCheckBox(self.groupBox_17)
        self.prop_checklegend_scaxis.setObjectName("prop_checklegend_scaxis")
        self.gridLayout_21.addWidget(self.prop_checklegend_scaxis, 0, 0, 1, 1)
        self.prop_legend_scaxis = QtWidgets.QLineEdit(self.groupBox_17)
        self.prop_legend_scaxis.setObjectName("prop_legend_scaxis")
        self.gridLayout_21.addWidget(self.prop_legend_scaxis, 0, 1, 1, 1)
        self.prop_checklegend_sccirc = QtWidgets.QCheckBox(self.groupBox_17)
        self.prop_checklegend_sccirc.setObjectName("prop_checklegend_sccirc")
        self.gridLayout_21.addWidget(self.prop_checklegend_sccirc, 1, 0, 1, 1)
        self.prop_legend_sccirc = QtWidgets.QLineEdit(self.groupBox_17)
        self.prop_legend_sccirc.setObjectName("prop_legend_sccirc")
        self.gridLayout_21.addWidget(self.prop_legend_sccirc, 1, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_17)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.show_auttitude_data_source = QtWidgets.QTextEdit(self.tab_4)
        self.show_auttitude_data_source.setObjectName("show_auttitude_data_source")
        self.horizontalLayout_7.addWidget(self.show_auttitude_data_source)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.apply = QtWidgets.QPushButton(Dialog)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.ok_button.clicked.connect(Dialog.accept)
        self.cancel_button.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.prop_legend_sccirc, self.prop_color_point_c)
        Dialog.setTabOrder(self.prop_color_point_c, self.prop_point_marker)
        Dialog.setTabOrder(self.prop_point_marker, self.prop_point_ms)
        Dialog.setTabOrder(self.prop_point_ms, self.prop_color_GC_colors)
        Dialog.setTabOrder(self.prop_color_GC_colors, self.prop_GC_linestyles)
        Dialog.setTabOrder(self.prop_GC_linestyles, self.prop_GC_linewidths)
        Dialog.setTabOrder(self.prop_GC_linewidths, self.prop_color_meanpoint_c)
        Dialog.setTabOrder(self.prop_color_meanpoint_c, self.prop_meanpoint_marker)
        Dialog.setTabOrder(self.prop_meanpoint_marker, self.prop_meanpoint_ms)
        Dialog.setTabOrder(self.prop_meanpoint_ms, self.prop_check_meanpoint)
        Dialog.setTabOrder(self.prop_check_meanpoint, self.prop_check_meanpointeiv)
        Dialog.setTabOrder(self.prop_check_meanpointeiv, self.prop_check_v1point)
        Dialog.setTabOrder(self.prop_check_v1point, self.prop_color_v1point_c)
        Dialog.setTabOrder(self.prop_color_v1point_c, self.prop_v1point_marker)
        Dialog.setTabOrder(self.prop_v1point_marker, self.prop_v1point_ms)
        Dialog.setTabOrder(self.prop_v1point_ms, self.prop_check_v1GC)
        Dialog.setTabOrder(self.prop_check_v1GC, self.prop_color_v1GC_colors)
        Dialog.setTabOrder(self.prop_color_v1GC_colors, self.prop_v1GC_linestyles)
        Dialog.setTabOrder(self.prop_v1GC_linestyles, self.prop_v1GC_linewidths)
        Dialog.setTabOrder(self.prop_v1GC_linewidths, self.prop_check_v2point)
        Dialog.setTabOrder(self.prop_check_v2point, self.prop_color_v2point_c)
        Dialog.setTabOrder(self.prop_color_v2point_c, self.prop_v2point_marker)
        Dialog.setTabOrder(self.prop_v2point_marker, self.prop_v2point_ms)
        Dialog.setTabOrder(self.prop_v2point_ms, self.prop_check_v2GC)
        Dialog.setTabOrder(self.prop_check_v2GC, self.prop_color_v2GC_colors)
        Dialog.setTabOrder(self.prop_color_v2GC_colors, self.prop_v2GC_linestyles)
        Dialog.setTabOrder(self.prop_v2GC_linestyles, self.prop_v2GC_linewidths)
        Dialog.setTabOrder(self.prop_v2GC_linewidths, self.prop_check_v3point)
        Dialog.setTabOrder(self.prop_check_v3point, self.prop_color_v3point_c)
        Dialog.setTabOrder(self.prop_color_v3point_c, self.prop_v3point_marker)
        Dialog.setTabOrder(self.prop_v3point_marker, self.prop_v3point_ms)
        Dialog.setTabOrder(self.prop_v3point_ms, self.prop_check_v3GC)
        Dialog.setTabOrder(self.prop_check_v3GC, self.prop_color_v3GC_colors)
        Dialog.setTabOrder(self.prop_color_v3GC_colors, self.prop_v3GC_linestyles)
        Dialog.setTabOrder(self.prop_v3GC_linestyles, self.prop_v3GC_linewidths)
        Dialog.setTabOrder(self.prop_v3GC_linewidths, self.prop_check_scaxis)
        Dialog.setTabOrder(self.prop_check_scaxis, self.prop_color_scaxis_c)
        Dialog.setTabOrder(self.prop_color_scaxis_c, self.prop_scaxis_marker)
        Dialog.setTabOrder(self.prop_scaxis_marker, self.prop_scaxis_ms)
        Dialog.setTabOrder(self.prop_scaxis_ms, self.prop_check_sccirc)
        Dialog.setTabOrder(self.prop_check_sccirc, self.prop_color_sccirc_colors)
        Dialog.setTabOrder(self.prop_color_sccirc_colors, self.prop_sccirc_linestyles)
        Dialog.setTabOrder(self.prop_sccirc_linestyles, self.prop_sccirc_linewidths)
        Dialog.setTabOrder(self.prop_sccirc_linewidths, self.prop_check_concentratesc)
        Dialog.setTabOrder(self.prop_check_concentratesc, self.prop_sccalc_eiv)
        Dialog.setTabOrder(self.prop_sccalc_eiv, self.show_auttitude_data_source)
        Dialog.setTabOrder(self.show_auttitude_data_source, self.cancel_button)
        Dialog.setTabOrder(self.cancel_button, self.apply)
        Dialog.setTabOrder(self.apply, self.show_auttitude_data_statistics)
        Dialog.setTabOrder(self.show_auttitude_data_statistics, self.ok_button)
        Dialog.setTabOrder(self.ok_button, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.prop_contour_check_drawover)
        Dialog.setTabOrder(self.prop_contour_check_drawover, self.prop_contour_linestyles)
        Dialog.setTabOrder(self.prop_contour_linestyles, self.prop_contour_line_linewidths)
        Dialog.setTabOrder(self.prop_contour_line_linewidths, self.prop_contour_check_solidline)
        Dialog.setTabOrder(self.prop_contour_check_solidline, self.prop_color_contour_line_colors)
        Dialog.setTabOrder(self.prop_color_contour_line_colors, self.prop_contour_check_gradientline)
        Dialog.setTabOrder(self.prop_contour_check_gradientline, self.prop_contour_line_cmap)
        Dialog.setTabOrder(self.prop_contour_line_cmap, self.prop_contour_check_fillcontours)
        Dialog.setTabOrder(self.prop_contour_check_fillcontours, self.prop_contour_cmap)
        Dialog.setTabOrder(self.prop_contour_cmap, self.prop_contour_cresolution)
        Dialog.setTabOrder(self.prop_contour_cresolution, self.prop_contour_antialiased)
        Dialog.setTabOrder(self.prop_contour_antialiased, self.prop_contour_check_minmax)
        Dialog.setTabOrder(self.prop_contour_check_minmax, self.prop_contour_check_zeromax)
        Dialog.setTabOrder(self.prop_contour_check_zeromax, self.prop_contour_ncontours)
        Dialog.setTabOrder(self.prop_contour_ncontours, self.prop_contour_check_customintervals)
        Dialog.setTabOrder(self.prop_contour_check_customintervals, self.prop_contour_intervals)
        Dialog.setTabOrder(self.prop_contour_intervals, self.prop_contour_calc_spacing)
        Dialog.setTabOrder(self.prop_contour_calc_spacing, self.prop_contour_check_fisher)
        Dialog.setTabOrder(self.prop_contour_check_fisher, self.prop_contour_calc_K)
        Dialog.setTabOrder(self.prop_contour_calc_K, self.prop_contour_check_scperc)
        Dialog.setTabOrder(self.prop_contour_check_scperc, self.prop_contour_calc_scperc)
        Dialog.setTabOrder(self.prop_contour_calc_scperc, self.prop_contour_check_scangle)
        Dialog.setTabOrder(self.prop_contour_check_scangle, self.prop_contour_calc_scangle)
        Dialog.setTabOrder(self.prop_contour_calc_scangle, self.prop_contour_check_autocount)
        Dialog.setTabOrder(self.prop_contour_check_autocount, self.prop_contour_check_robinjowett)
        Dialog.setTabOrder(self.prop_contour_check_robinjowett, self.prop_contour_check_digglefisher)
        Dialog.setTabOrder(self.prop_contour_check_digglefisher, self.prop_rose_check_standard)
        Dialog.setTabOrder(self.prop_rose_check_standard, self.prop_rose_binwidth)
        Dialog.setTabOrder(self.prop_rose_binwidth, self.prop_rose_offset)
        Dialog.setTabOrder(self.prop_rose_offset, self.prop_rose_check_continuous)
        Dialog.setTabOrder(self.prop_rose_check_continuous, self.prop_rose_aperture)
        Dialog.setTabOrder(self.prop_rose_aperture, self.prop_rose_check_weightmunro)
        Dialog.setTabOrder(self.prop_rose_check_weightmunro, self.prop_rose_weightmunro)
        Dialog.setTabOrder(self.prop_rose_weightmunro, self.prop_rose_spacing)
        Dialog.setTabOrder(self.prop_rose_spacing, self.prop_rose_offsetcont)
        Dialog.setTabOrder(self.prop_rose_offsetcont, self.prop_rose_check_dd)
        Dialog.setTabOrder(self.prop_rose_check_dd, self.prop_rose_check_dir)
        Dialog.setTabOrder(self.prop_rose_check_dir, self.prop_rose_check_diraxial)
        Dialog.setTabOrder(self.prop_rose_check_diraxial, self.prop_rose_check_weightcolumn)
        Dialog.setTabOrder(self.prop_rose_check_weightcolumn, self.prop_rose_weightcolumn)
        Dialog.setTabOrder(self.prop_rose_weightcolumn, self.prop_rose_check_mean)
        Dialog.setTabOrder(self.prop_rose_check_mean, self.prop_rose_mean_linestyle)
        Dialog.setTabOrder(self.prop_rose_mean_linestyle, self.prop_color_rose_mean_color)
        Dialog.setTabOrder(self.prop_color_rose_mean_color, self.prop_rose_mean_linewidth)
        Dialog.setTabOrder(self.prop_rose_mean_linewidth, self.prop_rose_check_confidence)
        Dialog.setTabOrder(self.prop_rose_check_confidence, self.prop_rose_confidence)
        Dialog.setTabOrder(self.prop_rose_confidence, self.prop_rose_check_petals)
        Dialog.setTabOrder(self.prop_rose_check_petals, self.prop_rose_check_petalsfill)
        Dialog.setTabOrder(self.prop_rose_check_petalsfill, self.prop_rose_check_petalsoutline)
        Dialog.setTabOrder(self.prop_rose_check_petalsoutline, self.prop_color_petals_facecolor)
        Dialog.setTabOrder(self.prop_color_petals_facecolor, self.prop_color_petals_edgecolor)
        Dialog.setTabOrder(self.prop_color_petals_edgecolor, self.prop_petals_linewidth)
        Dialog.setTabOrder(self.prop_petals_linewidth, self.prop_rose_check_kite)
        Dialog.setTabOrder(self.prop_rose_check_kite, self.prop_rose_check_kitefill)
        Dialog.setTabOrder(self.prop_rose_check_kitefill, self.prop_rose_check_kiteoutline)
        Dialog.setTabOrder(self.prop_rose_check_kiteoutline, self.prop_color_kite_facecolor)
        Dialog.setTabOrder(self.prop_color_kite_facecolor, self.prop_color_kite_edgecolor)
        Dialog.setTabOrder(self.prop_color_kite_edgecolor, self.prop_kite_linewidth)
        Dialog.setTabOrder(self.prop_kite_linewidth, self.prop_rose_check_lines)
        Dialog.setTabOrder(self.prop_rose_check_lines, self.prop_lines_linestyle)
        Dialog.setTabOrder(self.prop_lines_linestyle, self.prop_color_lines_color)
        Dialog.setTabOrder(self.prop_color_lines_color, self.prop_lines_linewidth)
        Dialog.setTabOrder(self.prop_lines_linewidth, self.prop_rose_check_meandeviation)
        Dialog.setTabOrder(self.prop_rose_check_meandeviation, self.prop_rose_check_360d)
        Dialog.setTabOrder(self.prop_rose_check_360d, self.prop_rose_check_interval)
        Dialog.setTabOrder(self.prop_rose_check_interval, self.prop_rose_intervalfrom)
        Dialog.setTabOrder(self.prop_rose_intervalfrom, self.prop_rose_intervalto)
        Dialog.setTabOrder(self.prop_rose_intervalto, self.prop_checklegend_point)
        Dialog.setTabOrder(self.prop_checklegend_point, self.prop_legend_point)
        Dialog.setTabOrder(self.prop_legend_point, self.prop_checklegend_GC)
        Dialog.setTabOrder(self.prop_checklegend_GC, self.prop_legend_GC)
        Dialog.setTabOrder(self.prop_legend_GC, self.prop_checklegend_meanpoint)
        Dialog.setTabOrder(self.prop_checklegend_meanpoint, self.prop_legend_meanpoint)
        Dialog.setTabOrder(self.prop_legend_meanpoint, self.prop_checklegend_v1point)
        Dialog.setTabOrder(self.prop_checklegend_v1point, self.prop_legend_v1point)
        Dialog.setTabOrder(self.prop_legend_v1point, self.prop_checklegend_v1GC)
        Dialog.setTabOrder(self.prop_checklegend_v1GC, self.prop_legend_v1GC)
        Dialog.setTabOrder(self.prop_legend_v1GC, self.prop_checklegend_v2point)
        Dialog.setTabOrder(self.prop_checklegend_v2point, self.prop_legend_v2point)
        Dialog.setTabOrder(self.prop_legend_v2point, self.prop_checklegend_v2GC)
        Dialog.setTabOrder(self.prop_checklegend_v2GC, self.prop_legend_v2GC)
        Dialog.setTabOrder(self.prop_legend_v2GC, self.prop_checklegend_v3point)
        Dialog.setTabOrder(self.prop_checklegend_v3point, self.prop_legend_v3point)
        Dialog.setTabOrder(self.prop_legend_v3point, self.prop_checklegend_v3GC)
        Dialog.setTabOrder(self.prop_checklegend_v3GC, self.prop_legend_v3GC)
        Dialog.setTabOrder(self.prop_legend_v3GC, self.prop_checklegend_scaxis)
        Dialog.setTabOrder(self.prop_checklegend_scaxis, self.prop_legend_scaxis)
        Dialog.setTabOrder(self.prop_legend_scaxis, self.prop_checklegend_sccirc)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Poles"))
        self.label_2.setText(_translate("Dialog", "Symbol"))
        self.label_3.setText(_translate("Dialog", "Size"))
        self.label.setText(_translate("Dialog", "Color"))
        self.prop_point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_point_marker.setItemText(19, _translate("Dialog", "4"))
        self.groupBox_2.setTitle(_translate("Dialog", "Great Circles"))
        self.label_4.setText(_translate("Dialog", "Symbol"))
        self.label_6.setText(_translate("Dialog", "Width"))
        self.label_5.setText(_translate("Dialog", "Color"))
        self.prop_GC_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_GC_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_GC_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_GC_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.groupBox_4.setTitle(_translate("Dialog", "Mean Vector"))
        self.label_13.setText(_translate("Dialog", "Symbol"))
        self.label_15.setText(_translate("Dialog", "Color"))
        self.label_14.setText(_translate("Dialog", "Size"))
        self.prop_meanpoint_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_meanpoint_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_meanpoint_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_meanpoint_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_meanpoint_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_meanpoint_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_meanpoint_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_meanpoint_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_meanpoint_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_meanpoint_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_meanpoint_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_meanpoint_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_meanpoint_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_meanpoint_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_meanpoint_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_meanpoint_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_meanpoint_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_meanpoint_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_meanpoint_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_meanpoint_marker.setItemText(19, _translate("Dialog", "4"))
        self.prop_check_meanpoint.setText(_translate("Dialog", "Plot Mean"))
        self.prop_check_meanpointeiv.setText(_translate("Dialog", "Mean around first eigenvector"))
        self.groupBox_3.setTitle(_translate("Dialog", "Eigenvectors"))
        self.prop_check_v1point.setText(_translate("Dialog", "Pole"))
        self.prop_check_v1GC.setText(_translate("Dialog", "Great Circle"))
        self.label_8.setText(_translate("Dialog", "Size"))
        self.prop_v1point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_v1point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_v1point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_v1point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_v1point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_v1point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_v1point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_v1point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_v1point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_v1point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_v1point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_v1point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_v1point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_v1point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_v1point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_v1point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_v1point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_v1point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_v1point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_v1point_marker.setItemText(19, _translate("Dialog", "4"))
        self.label_9.setText(_translate("Dialog", "Color"))
        self.label_7.setText(_translate("Dialog", "Symbol"))
        self.prop_v1GC_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_v1GC_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_v1GC_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_v1GC_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.prop_check_v2GC.setText(_translate("Dialog", "Great Circle"))
        self.prop_check_v2point.setText(_translate("Dialog", "Pole"))
        self.label_11.setText(_translate("Dialog", "Second"))
        self.prop_v2point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_v2point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_v2point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_v2point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_v2point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_v2point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_v2point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_v2point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_v2point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_v2point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_v2point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_v2point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_v2point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_v2point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_v2point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_v2point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_v2point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_v2point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_v2point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_v2point_marker.setItemText(19, _translate("Dialog", "4"))
        self.prop_check_v3point.setText(_translate("Dialog", "Pole"))
        self.prop_v3point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_v3point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_v3point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_v3point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_v3point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_v3point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_v3point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_v3point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_v3point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_v3point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_v3point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_v3point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_v3point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_v3point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_v3point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_v3point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_v3point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_v3point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_v3point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_v3point_marker.setItemText(19, _translate("Dialog", "4"))
        self.prop_check_v3GC.setText(_translate("Dialog", "Great Circle"))
        self.label_12.setText(_translate("Dialog", "Third"))
        self.prop_v2GC_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_v2GC_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_v2GC_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_v2GC_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_10.setText(_translate("Dialog", "First"))
        self.prop_v3GC_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_v3GC_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_v3GC_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_v3GC_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.groupBox_11.setTitle(_translate("Dialog", "Fitted Small Circle"))
        self.label_41.setText(_translate("Dialog", "Color"))
        self.prop_check_scaxis.setText(_translate("Dialog", "Axis"))
        self.label_40.setText(_translate("Dialog", "Symbol"))
        self.prop_scaxis_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_scaxis_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_scaxis_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_scaxis_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_scaxis_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_scaxis_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_scaxis_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_scaxis_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_scaxis_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_scaxis_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_scaxis_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_scaxis_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_scaxis_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_scaxis_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_scaxis_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_scaxis_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_scaxis_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_scaxis_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_scaxis_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_scaxis_marker.setItemText(19, _translate("Dialog", "4"))
        self.label_43.setText(_translate("Dialog", "Size"))
        self.prop_sccirc_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_sccirc_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_sccirc_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_sccirc_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.prop_check_sccirc.setText(_translate("Dialog", "Circle"))
        self.prop_check_concentratesc.setText(_translate("Dialog", "Concentrate Data around Eigenvector:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Projection"))
        self.groupBox_12.setTitle(_translate("Dialog", "Graphic properties"))
        self.prop_contour_check_gradientline.setText(_translate("Dialog", "Gradient"))
        self.prop_contour_check_fillcontours.setText(_translate("Dialog", "Fill contours"))
        self.prop_contour_cmap.setItemText(0, _translate("Dialog", "jet"))
        self.prop_contour_cmap.setItemText(1, _translate("Dialog", "jet_r"))
        self.prop_contour_cmap.setItemText(2, _translate("Dialog", "hsv"))
        self.prop_contour_cmap.setItemText(3, _translate("Dialog", "hsv_r"))
        self.prop_contour_cmap.setItemText(4, _translate("Dialog", "Greys"))
        self.prop_contour_cmap.setItemText(5, _translate("Dialog", "Greys_r"))
        self.prop_contour_cmap.setItemText(6, _translate("Dialog", "Blues"))
        self.prop_contour_cmap.setItemText(7, _translate("Dialog", "Blues_r"))
        self.prop_contour_cmap.setItemText(8, _translate("Dialog", "Greens"))
        self.prop_contour_cmap.setItemText(9, _translate("Dialog", "Greens_r"))
        self.prop_contour_cmap.setItemText(10, _translate("Dialog", "Oranges"))
        self.prop_contour_cmap.setItemText(11, _translate("Dialog", "Oranges_r"))
        self.prop_contour_cmap.setItemText(12, _translate("Dialog", "Reds"))
        self.prop_contour_cmap.setItemText(13, _translate("Dialog", "Reds_r"))
        self.label_30.setText(_translate("Dialog", "Width"))
        self.prop_contour_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_contour_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_contour_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_contour_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_23.setText(_translate("Dialog", "Style"))
        self.prop_contour_check_drawover.setText(_translate("Dialog", "Contour Lines"))
        self.prop_contour_line_cmap.setItemText(0, _translate("Dialog", "jet"))
        self.prop_contour_line_cmap.setItemText(1, _translate("Dialog", "jet_r"))
        self.prop_contour_line_cmap.setItemText(2, _translate("Dialog", "hsv"))
        self.prop_contour_line_cmap.setItemText(3, _translate("Dialog", "hsv_r"))
        self.prop_contour_line_cmap.setItemText(4, _translate("Dialog", "Greys"))
        self.prop_contour_line_cmap.setItemText(5, _translate("Dialog", "Greys_r"))
        self.prop_contour_line_cmap.setItemText(6, _translate("Dialog", "Blues"))
        self.prop_contour_line_cmap.setItemText(7, _translate("Dialog", "Blues_r"))
        self.prop_contour_line_cmap.setItemText(8, _translate("Dialog", "Greens"))
        self.prop_contour_line_cmap.setItemText(9, _translate("Dialog", "Greens_r"))
        self.prop_contour_line_cmap.setItemText(10, _translate("Dialog", "Oranges"))
        self.prop_contour_line_cmap.setItemText(11, _translate("Dialog", "Oranges_r"))
        self.prop_contour_line_cmap.setItemText(12, _translate("Dialog", "Reds"))
        self.prop_contour_line_cmap.setItemText(13, _translate("Dialog", "Reds_r"))
        self.prop_contour_check_solidline.setText(_translate("Dialog", "Solid Color"))
        self.label_36.setText(_translate("Dialog", "Resolution"))
        self.prop_contour_antialiased.setText(_translate("Dialog", "Antialiased"))
        self.groupBox_13.setTitle(_translate("Dialog", "Contour Intervals"))
        self.prop_contour_check_minmax.setText(_translate("Dialog", "From minimum to maximum"))
        self.prop_contour_check_zeromax.setText(_translate("Dialog", "From zero to maximum"))
        self.label_31.setText(_translate("Dialog", "Number of contours"))
        self.prop_contour_check_customintervals.setText(_translate("Dialog", "Custom list"))
        self.groupBox_14.setTitle(_translate("Dialog", "Contour Method"))
        self.label_32.setText(_translate("Dialog", "Grid spacing"))
        self.prop_contour_check_fisher.setText(_translate("Dialog", "Fisher Distribution"))
        self.label_33.setText(_translate("Dialog", "(K)"))
        self.prop_contour_check_scperc.setText(_translate("Dialog", "Small circle count"))
        self.label_34.setText(_translate("Dialog", "(% area)"))
        self.prop_contour_check_scangle.setText(_translate("Dialog", "Small circle count"))
        self.label_35.setText(_translate("Dialog", "(angle)"))
        self.prop_contour_check_autocount.setText(_translate("Dialog", "Estimate parameters from data"))
        self.groupBox_15.setTitle(_translate("Dialog", "Estimation Method"))
        self.prop_contour_check_robinjowett.setText(_translate("Dialog", "Robin && Jowett 1986"))
        self.prop_contour_check_digglefisher.setText(_translate("Dialog", "Diggle && Fisher 1985"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Contours"))
        self.groupBox_9.setTitle(_translate("Dialog", "Mean direction"))
        self.label_25.setText(_translate("Dialog", "Color"))
        self.prop_rose_check_mean.setText(_translate("Dialog", "Show"))
        self.label_26.setText(_translate("Dialog", "Size"))
        self.prop_rose_mean_linestyle.setItemText(0, _translate("Dialog", "-"))
        self.prop_rose_mean_linestyle.setItemText(1, _translate("Dialog", ":"))
        self.prop_rose_mean_linestyle.setItemText(2, _translate("Dialog", "--"))
        self.prop_rose_mean_linestyle.setItemText(3, _translate("Dialog", "-."))
        self.label_37.setText(_translate("Dialog", "Style"))
        self.prop_rose_check_confidence.setText(_translate("Dialog", "Confidence Interval (%)"))
        self.groupBox_6.setTitle(_translate("Dialog", "Type"))
        self.prop_rose_check_360d.setText(_translate("Dialog", "360 degrees"))
        self.prop_rose_check_180d.setText(_translate("Dialog", "180 degrees"))
        self.prop_rose_180half.setItemText(0, _translate("Dialog", "N"))
        self.prop_rose_180half.setItemText(1, _translate("Dialog", "S"))
        self.prop_rose_check_interval.setText(_translate("Dialog", "Interval:"))
        self.groupBox_16.setTitle(_translate("Dialog", "Counting Method"))
        self.prop_rose_check_standard.setText(_translate("Dialog", "Standard"))
        self.label_18.setText(_translate("Dialog", "Bin Width"))
        self.label_24.setText(_translate("Dialog", "Offset"))
        self.label_19.setText(_translate("Dialog", "Aperture"))
        self.prop_rose_check_continuous.setText(_translate("Dialog", "Continuous"))
        self.prop_rose_check_weightmunro.setText(_translate("Dialog", "Weight"))
        self.label_38.setText(_translate("Dialog", "Spacing"))
        self.label_39.setText(_translate("Dialog", "Offset"))
        self.groupBox_7.setTitle(_translate("Dialog", "Graphic Properties"))
        self.prop_rose_check_petalsfill.setText(_translate("Dialog", "Fill"))
        self.prop_rose_check_petalsoutline.setText(_translate("Dialog", "Outline"))
        self.label_20.setText(_translate("Dialog", "Width"))
        self.prop_rose_check_petals.setText(_translate("Dialog", "Petals"))
        self.prop_rose_check_kitefill.setText(_translate("Dialog", "Fill"))
        self.prop_rose_check_kiteoutline.setText(_translate("Dialog", "Outline"))
        self.label_22.setText(_translate("Dialog", "Width"))
        self.prop_rose_check_kite.setText(_translate("Dialog", "Kite"))
        self.label_29.setText(_translate("Dialog", "Style"))
        self.label_28.setText(_translate("Dialog", "Color"))
        self.label_27.setText(_translate("Dialog", "Size"))
        self.prop_rose_check_lines.setText(_translate("Dialog", "Lines"))
        self.prop_lines_linestyle.setItemText(0, _translate("Dialog", ":"))
        self.prop_lines_linestyle.setItemText(1, _translate("Dialog", "-"))
        self.prop_lines_linestyle.setItemText(2, _translate("Dialog", "--"))
        self.prop_lines_linestyle.setItemText(3, _translate("Dialog", "-."))
        self.prop_rose_check_meandeviation.setText(_translate("Dialog", "Mean Deviation"))
        self.groupBox_5.setTitle(_translate("Dialog", "Data"))
        self.prop_rose_check_dd.setText(_translate("Dialog", "dip direction"))
        self.prop_rose_check_dir.setText(_translate("Dialog", "strike (RHR)"))
        self.prop_rose_check_diraxial.setText(_translate("Dialog", "Axial"))
        self.prop_rose_check_weightcolumn.setText(_translate("Dialog", "Weight by column:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roseDiagram), _translate("Dialog", "Rose Diagram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Statistics"))
        self.groupBox_8.setTitle(_translate("Dialog", "Data Legend"))
        self.prop_checklegend_GC.setText(_translate("Dialog", "Great Circles"))
        self.prop_checklegend_point.setText(_translate("Dialog", "Poles"))
        self.prop_checklegend_meanpoint.setText(_translate("Dialog", "Mean"))
        self.groupBox_10.setTitle(_translate("Dialog", "Eigenvector Legend"))
        self.label_16.setText(_translate("Dialog", "First"))
        self.prop_checklegend_v1point.setText(_translate("Dialog", "Poles"))
        self.prop_checklegend_v1GC.setText(_translate("Dialog", "Great Circles"))
        self.label_17.setText(_translate("Dialog", "Second"))
        self.prop_checklegend_v2point.setText(_translate("Dialog", "Poles"))
        self.prop_checklegend_v2GC.setText(_translate("Dialog", "Great Circles"))
        self.label_21.setText(_translate("Dialog", "Third"))
        self.prop_checklegend_v3point.setText(_translate("Dialog", "Poles"))
        self.prop_checklegend_v3GC.setText(_translate("Dialog", "Great Circles"))
        self.groupBox_17.setTitle(_translate("Dialog", "Small Circle Legend"))
        self.prop_checklegend_scaxis.setText(_translate("Dialog", "Axis"))
        self.prop_checklegend_sccirc.setText(_translate("Dialog", "Small Circle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Data Source"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.apply.setText(_translate("Dialog", "Apply"))

