# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/rotate_data.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(283, 185)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.A = QtWidgets.QComboBox(Dialog)
        self.A.setObjectName("A")
        self.verticalLayout.addWidget(self.A)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.trend = QtWidgets.QDoubleSpinBox(Dialog)
        self.trend.setMinimum(-360.0)
        self.trend.setMaximum(360.0)
        self.trend.setObjectName("trend")
        self.gridLayout.addWidget(self.trend, 1, 1, 1, 1)
        self.plunge = QtWidgets.QDoubleSpinBox(Dialog)
        self.plunge.setMinimum(-90.0)
        self.plunge.setMaximum(90.0)
        self.plunge.setObjectName("plunge")
        self.gridLayout.addWidget(self.plunge, 1, 2, 1, 1)
        self.angle = QtWidgets.QDoubleSpinBox(Dialog)
        self.angle.setMinimum(-360.0)
        self.angle.setMaximum(360.0)
        self.angle.setObjectName("angle")
        self.gridLayout.addWidget(self.angle, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.savename = QtWidgets.QLineEdit(Dialog)
        self.savename.setObjectName("savename")
        self.horizontalLayout.addWidget(self.savename)
        self.browse = QtWidgets.QPushButton(Dialog)
        self.browse.setObjectName("browse")
        self.horizontalLayout.addWidget(self.browse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.keep = QtWidgets.QCheckBox(Dialog)
        self.keep.setChecked(True)
        self.keep.setObjectName("keep")
        self.horizontalLayout_3.addWidget(self.keep)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.ok_button.clicked.connect(Dialog.accept)
        self.cancel_button.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Rotate Data"))
        self.label_3.setText(_translate("Dialog", "Trend"))
        self.label_4.setText(_translate("Dialog", "Plunge"))
        self.label_2.setText(_translate("Dialog", "Angle"))
        self.label.setText(_translate("Dialog", "Axis"))
        self.browse.setText(_translate("Dialog", "Browse..."))
        self.keep.setText(_translate("Dialog", "Load rotated data"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))

