# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\slope_properties.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 523)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.prop_data_attitude = QtWidgets.QLineEdit(self.groupBox_3)
        self.prop_data_attitude.setObjectName("prop_data_attitude")
        self.verticalLayout_2.addWidget(self.prop_data_attitude)
        self.prop_data_strike = QtWidgets.QCheckBox(self.groupBox_3)
        self.prop_data_strike.setObjectName("prop_data_strike")
        self.verticalLayout_2.addWidget(self.prop_data_strike)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout.setObjectName("formLayout")
        self.prop_checklegend_point = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_point.setObjectName("prop_checklegend_point")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_point)
        self.prop_legend_point = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_point.setObjectName("prop_legend_point")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prop_legend_point)
        self.prop_checklegend_GC = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_GC.setObjectName("prop_checklegend_GC")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_GC)
        self.prop_legend_GC = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_GC.setObjectName("prop_legend_GC")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prop_legend_GC)
        self.prop_checklegend_daylight = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_daylight.setObjectName("prop_checklegend_daylight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_daylight)
        self.prop_legend_daylight = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_daylight.setObjectName("prop_legend_daylight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prop_legend_daylight)
        self.prop_checklegend_lateral = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_lateral.setObjectName("prop_checklegend_lateral")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_lateral)
        self.prop_legend_lateral = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_lateral.setObjectName("prop_legend_lateral")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prop_legend_lateral)
        self.prop_checklegend_planecone = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_planecone.setObjectName("prop_checklegend_planecone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_planecone)
        self.prop_legend_planecone = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_planecone.setObjectName("prop_legend_planecone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.prop_legend_planecone)
        self.prop_checklegend_polecone = QtWidgets.QCheckBox(self.groupBox_8)
        self.prop_checklegend_polecone.setObjectName("prop_checklegend_polecone")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.prop_checklegend_polecone)
        self.prop_legend_polecone = QtWidgets.QLineEdit(self.groupBox_8)
        self.prop_legend_polecone.setObjectName("prop_legend_polecone")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.prop_legend_polecone)
        self.gridLayout_4.addWidget(self.groupBox_8, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.prop_color_point_c = QtWidgets.QPushButton(self.groupBox)
        self.prop_color_point_c.setText("")
        self.prop_color_point_c.setObjectName("prop_color_point_c")
        self.gridLayout.addWidget(self.prop_color_point_c, 1, 0, 1, 1)
        self.prop_point_marker = QtWidgets.QComboBox(self.groupBox)
        self.prop_point_marker.setObjectName("prop_point_marker")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.prop_point_marker.addItem("")
        self.gridLayout.addWidget(self.prop_point_marker, 1, 1, 1, 1)
        self.prop_point_ms = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.prop_point_ms.setObjectName("prop_point_ms")
        self.gridLayout.addWidget(self.prop_point_ms, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.prop_GC_linestyles = QtWidgets.QComboBox(self.groupBox_2)
        self.prop_GC_linestyles.setObjectName("prop_GC_linestyles")
        self.prop_GC_linestyles.addItem("")
        self.prop_GC_linestyles.addItem("")
        self.prop_GC_linestyles.addItem("")
        self.prop_GC_linestyles.addItem("")
        self.gridLayout_2.addWidget(self.prop_GC_linestyles, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.prop_color_GC_colors = QtWidgets.QPushButton(self.groupBox_2)
        self.prop_color_GC_colors.setText("")
        self.prop_color_GC_colors.setObjectName("prop_color_GC_colors")
        self.gridLayout_2.addWidget(self.prop_color_GC_colors, 1, 0, 1, 1)
        self.prop_GC_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.prop_GC_linewidths.setObjectName("prop_GC_linewidths")
        self.gridLayout_2.addWidget(self.prop_GC_linewidths, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 2)
        self.prop_polecone_linestyles = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_polecone_linestyles.setObjectName("prop_polecone_linestyles")
        self.prop_polecone_linestyles.addItem("")
        self.prop_polecone_linestyles.addItem("")
        self.prop_polecone_linestyles.addItem("")
        self.prop_polecone_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_polecone_linestyles, 5, 2, 1, 1)
        self.prop_data_friction = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_data_friction.setMaximum(90.0)
        self.prop_data_friction.setObjectName("prop_data_friction")
        self.gridLayout_3.addWidget(self.prop_data_friction, 6, 2, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 2)
        self.prop_data_lateral = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_data_lateral.setMaximum(90.0)
        self.prop_data_lateral.setObjectName("prop_data_lateral")
        self.gridLayout_3.addWidget(self.prop_data_lateral, 3, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.prop_daylight_linestyles = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_daylight_linestyles.setObjectName("prop_daylight_linestyles")
        self.prop_daylight_linestyles.addItem("")
        self.prop_daylight_linestyles.addItem("")
        self.prop_daylight_linestyles.addItem("")
        self.prop_daylight_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_daylight_linestyles, 1, 2, 1, 1)
        self.prop_daylight_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_daylight_linewidths.setObjectName("prop_daylight_linewidths")
        self.gridLayout_3.addWidget(self.prop_daylight_linewidths, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.prop_color_lateral_colors = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_lateral_colors.setText("")
        self.prop_color_lateral_colors.setObjectName("prop_color_lateral_colors")
        self.gridLayout_3.addWidget(self.prop_color_lateral_colors, 2, 1, 1, 1)
        self.prop_lateral_linestyles = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_lateral_linestyles.setObjectName("prop_lateral_linestyles")
        self.prop_lateral_linestyles.addItem("")
        self.prop_lateral_linestyles.addItem("")
        self.prop_lateral_linestyles.addItem("")
        self.prop_lateral_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_lateral_linestyles, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.prop_color_daylight_colors = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_daylight_colors.setText("")
        self.prop_color_daylight_colors.setObjectName("prop_color_daylight_colors")
        self.gridLayout_3.addWidget(self.prop_color_daylight_colors, 1, 1, 1, 1)
        self.prop_lateral_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_lateral_linewidths.setObjectName("prop_lateral_linewidths")
        self.gridLayout_3.addWidget(self.prop_lateral_linewidths, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.prop_color_planecone_colors = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_planecone_colors.setText("")
        self.prop_color_planecone_colors.setObjectName("prop_color_planecone_colors")
        self.gridLayout_3.addWidget(self.prop_color_planecone_colors, 4, 1, 1, 1)
        self.prop_planecone_linestyles = QtWidgets.QComboBox(self.groupBox_4)
        self.prop_planecone_linestyles.setObjectName("prop_planecone_linestyles")
        self.prop_planecone_linestyles.addItem("")
        self.prop_planecone_linestyles.addItem("")
        self.prop_planecone_linestyles.addItem("")
        self.prop_planecone_linestyles.addItem("")
        self.gridLayout_3.addWidget(self.prop_planecone_linestyles, 4, 2, 1, 1)
        self.prop_color_polecone_colors = QtWidgets.QPushButton(self.groupBox_4)
        self.prop_color_polecone_colors.setText("")
        self.prop_color_polecone_colors.setObjectName("prop_color_polecone_colors")
        self.gridLayout_3.addWidget(self.prop_color_polecone_colors, 5, 1, 1, 1)
        self.prop_planecone_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_planecone_linewidths.setObjectName("prop_planecone_linewidths")
        self.gridLayout_3.addWidget(self.prop_planecone_linewidths, 4, 3, 1, 1)
        self.prop_polecone_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.prop_polecone_linewidths.setObjectName("prop_polecone_linewidths")
        self.gridLayout_3.addWidget(self.prop_polecone_linewidths, 5, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.apply = QtWidgets.QPushButton(Dialog)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.ok_button.clicked.connect(Dialog.accept)
        self.cancel_button.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.prop_data_attitude, self.prop_data_strike)
        Dialog.setTabOrder(self.prop_data_strike, self.prop_color_point_c)
        Dialog.setTabOrder(self.prop_color_point_c, self.prop_point_marker)
        Dialog.setTabOrder(self.prop_point_marker, self.prop_point_ms)
        Dialog.setTabOrder(self.prop_point_ms, self.prop_color_GC_colors)
        Dialog.setTabOrder(self.prop_color_GC_colors, self.prop_GC_linestyles)
        Dialog.setTabOrder(self.prop_GC_linestyles, self.prop_GC_linewidths)
        Dialog.setTabOrder(self.prop_GC_linewidths, self.prop_color_daylight_colors)
        Dialog.setTabOrder(self.prop_color_daylight_colors, self.prop_daylight_linestyles)
        Dialog.setTabOrder(self.prop_daylight_linestyles, self.prop_daylight_linewidths)
        Dialog.setTabOrder(self.prop_daylight_linewidths, self.prop_color_lateral_colors)
        Dialog.setTabOrder(self.prop_color_lateral_colors, self.prop_lateral_linestyles)
        Dialog.setTabOrder(self.prop_lateral_linestyles, self.prop_lateral_linewidths)
        Dialog.setTabOrder(self.prop_lateral_linewidths, self.prop_data_lateral)
        Dialog.setTabOrder(self.prop_data_lateral, self.prop_color_planecone_colors)
        Dialog.setTabOrder(self.prop_color_planecone_colors, self.prop_planecone_linestyles)
        Dialog.setTabOrder(self.prop_planecone_linestyles, self.prop_planecone_linewidths)
        Dialog.setTabOrder(self.prop_planecone_linewidths, self.prop_color_polecone_colors)
        Dialog.setTabOrder(self.prop_color_polecone_colors, self.prop_polecone_linestyles)
        Dialog.setTabOrder(self.prop_polecone_linestyles, self.prop_polecone_linewidths)
        Dialog.setTabOrder(self.prop_polecone_linewidths, self.prop_data_friction)
        Dialog.setTabOrder(self.prop_data_friction, self.prop_checklegend_point)
        Dialog.setTabOrder(self.prop_checklegend_point, self.prop_legend_point)
        Dialog.setTabOrder(self.prop_legend_point, self.prop_checklegend_GC)
        Dialog.setTabOrder(self.prop_checklegend_GC, self.prop_legend_GC)
        Dialog.setTabOrder(self.prop_legend_GC, self.prop_checklegend_daylight)
        Dialog.setTabOrder(self.prop_checklegend_daylight, self.prop_legend_daylight)
        Dialog.setTabOrder(self.prop_legend_daylight, self.prop_checklegend_lateral)
        Dialog.setTabOrder(self.prop_checklegend_lateral, self.prop_legend_lateral)
        Dialog.setTabOrder(self.prop_legend_lateral, self.prop_checklegend_planecone)
        Dialog.setTabOrder(self.prop_checklegend_planecone, self.prop_legend_planecone)
        Dialog.setTabOrder(self.prop_legend_planecone, self.prop_checklegend_polecone)
        Dialog.setTabOrder(self.prop_checklegend_polecone, self.prop_legend_polecone)
        Dialog.setTabOrder(self.prop_legend_polecone, self.ok_button)
        Dialog.setTabOrder(self.ok_button, self.cancel_button)
        Dialog.setTabOrder(self.cancel_button, self.apply)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "Attitude"))
        self.prop_data_strike.setText(_translate("Dialog", "Strike"))
        self.groupBox_8.setTitle(_translate("Dialog", "Data Legend"))
        self.prop_checklegend_point.setText(_translate("Dialog", "Pole"))
        self.prop_checklegend_GC.setText(_translate("Dialog", "Great Circle"))
        self.prop_checklegend_daylight.setText(_translate("Dialog", "Daylight Envelope"))
        self.prop_checklegend_lateral.setText(_translate("Dialog", "Lateral Limit"))
        self.prop_checklegend_planecone.setText(_translate("Dialog", "Plane Friction Cone"))
        self.prop_checklegend_polecone.setText(_translate("Dialog", "Pole Friction Cone"))
        self.groupBox.setTitle(_translate("Dialog", "Pole"))
        self.label_2.setText(_translate("Dialog", "Symbol"))
        self.label_3.setText(_translate("Dialog", "Size"))
        self.label.setText(_translate("Dialog", "Color"))
        self.prop_point_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_point_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_point_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_point_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_point_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_point_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_point_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_point_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_point_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_point_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_point_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_point_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_point_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_point_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_point_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_point_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_point_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_point_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_point_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_point_marker.setItemText(19, _translate("Dialog", "4"))
        self.groupBox_2.setTitle(_translate("Dialog", "Great Circle"))
        self.prop_GC_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_GC_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_GC_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_GC_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_4.setText(_translate("Dialog", "Symbol"))
        self.label_6.setText(_translate("Dialog", "Width"))
        self.label_5.setText(_translate("Dialog", "Color"))
        self.groupBox_4.setTitle(_translate("Dialog", "Geometric Analysis"))
        self.label_14.setText(_translate("Dialog", "friction angle"))
        self.prop_polecone_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_polecone_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_polecone_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_polecone_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_13.setText(_translate("Dialog", "limit angle"))
        self.label_8.setText(_translate("Dialog", "Width"))
        self.label_10.setText(_translate("Dialog", "Daylight Envelope"))
        self.label_9.setText(_translate("Dialog", "Color"))
        self.prop_daylight_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_daylight_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_daylight_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_daylight_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_11.setText(_translate("Dialog", "Lateral Limit"))
        self.prop_lateral_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_lateral_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_lateral_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_lateral_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_7.setText(_translate("Dialog", "Symbol"))
        self.label_12.setText(_translate("Dialog", "Plane Friction Cone"))
        self.prop_planecone_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_planecone_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_planecone_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_planecone_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.label_15.setText(_translate("Dialog", "Pole Friction Cone"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.apply.setText(_translate("Dialog", "Apply"))

