# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\smallcircle_properties.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 502)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.prop_color_scaxis_c = QtWidgets.QPushButton(self.groupBox)
        self.prop_color_scaxis_c.setText("")
        self.prop_color_scaxis_c.setObjectName("prop_color_scaxis_c")
        self.gridLayout.addWidget(self.prop_color_scaxis_c, 1, 0, 1, 1)
        self.prop_scaxis_marker = QtWidgets.QComboBox(self.groupBox)
        self.prop_scaxis_marker.setObjectName("prop_scaxis_marker")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.prop_scaxis_marker.addItem("")
        self.gridLayout.addWidget(self.prop_scaxis_marker, 1, 1, 1, 1)
        self.prop_scaxis_ms = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.prop_scaxis_ms.setObjectName("prop_scaxis_ms")
        self.gridLayout.addWidget(self.prop_scaxis_ms, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.prop_color_sccirc_colors = QtWidgets.QPushButton(self.groupBox_2)
        self.prop_color_sccirc_colors.setText("")
        self.prop_color_sccirc_colors.setObjectName("prop_color_sccirc_colors")
        self.gridLayout_2.addWidget(self.prop_color_sccirc_colors, 1, 0, 1, 1)
        self.prop_sccirc_linestyles = QtWidgets.QComboBox(self.groupBox_2)
        self.prop_sccirc_linestyles.setObjectName("prop_sccirc_linestyles")
        self.prop_sccirc_linestyles.addItem("")
        self.prop_sccirc_linestyles.addItem("")
        self.prop_sccirc_linestyles.addItem("")
        self.prop_sccirc_linestyles.addItem("")
        self.gridLayout_2.addWidget(self.prop_sccirc_linestyles, 1, 1, 1, 1)
        self.prop_sccirc_linewidths = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.prop_sccirc_linewidths.setObjectName("prop_sccirc_linewidths")
        self.gridLayout_2.addWidget(self.prop_sccirc_linewidths, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(418, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.show_auttitude_data_statistics = QtWidgets.QTextEdit(self.tab_3)
        self.show_auttitude_data_statistics.setObjectName("show_auttitude_data_statistics")
        self.horizontalLayout_6.addWidget(self.show_auttitude_data_statistics)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.prop_checklegend_scaxis = QtWidgets.QCheckBox(self.groupBox_17)
        self.prop_checklegend_scaxis.setObjectName("prop_checklegend_scaxis")
        self.gridLayout_21.addWidget(self.prop_checklegend_scaxis, 0, 0, 1, 1)
        self.prop_legend_scaxis = QtWidgets.QLineEdit(self.groupBox_17)
        self.prop_legend_scaxis.setObjectName("prop_legend_scaxis")
        self.gridLayout_21.addWidget(self.prop_legend_scaxis, 0, 1, 1, 1)
        self.prop_checklegend_sccirc = QtWidgets.QCheckBox(self.groupBox_17)
        self.prop_checklegend_sccirc.setObjectName("prop_checklegend_sccirc")
        self.gridLayout_21.addWidget(self.prop_checklegend_sccirc, 1, 0, 1, 1)
        self.prop_legend_sccirc = QtWidgets.QLineEdit(self.groupBox_17)
        self.prop_legend_sccirc.setObjectName("prop_legend_sccirc")
        self.gridLayout_21.addWidget(self.prop_legend_sccirc, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_17)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.show_auttitude_data_source = QtWidgets.QTextEdit(self.tab_4)
        self.show_auttitude_data_source.setObjectName("show_auttitude_data_source")
        self.horizontalLayout_7.addWidget(self.show_auttitude_data_source)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.apply = QtWidgets.QPushButton(Dialog)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.ok_button.clicked.connect(Dialog.accept)
        self.cancel_button.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.prop_legend_sccirc, self.show_auttitude_data_source)
        Dialog.setTabOrder(self.show_auttitude_data_source, self.cancel_button)
        Dialog.setTabOrder(self.cancel_button, self.apply)
        Dialog.setTabOrder(self.apply, self.show_auttitude_data_statistics)
        Dialog.setTabOrder(self.show_auttitude_data_statistics, self.ok_button)
        Dialog.setTabOrder(self.ok_button, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.prop_checklegend_scaxis)
        Dialog.setTabOrder(self.prop_checklegend_scaxis, self.prop_legend_scaxis)
        Dialog.setTabOrder(self.prop_legend_scaxis, self.prop_checklegend_sccirc)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Axes"))
        self.label_2.setText(_translate("Dialog", "Symbol"))
        self.label_3.setText(_translate("Dialog", "Size"))
        self.label.setText(_translate("Dialog", "Color"))
        self.prop_scaxis_marker.setItemText(0, _translate("Dialog", "o"))
        self.prop_scaxis_marker.setItemText(1, _translate("Dialog", "^"))
        self.prop_scaxis_marker.setItemText(2, _translate("Dialog", "v"))
        self.prop_scaxis_marker.setItemText(3, _translate("Dialog", "<"))
        self.prop_scaxis_marker.setItemText(4, _translate("Dialog", ">"))
        self.prop_scaxis_marker.setItemText(5, _translate("Dialog", "s"))
        self.prop_scaxis_marker.setItemText(6, _translate("Dialog", "+"))
        self.prop_scaxis_marker.setItemText(7, _translate("Dialog", "x"))
        self.prop_scaxis_marker.setItemText(8, _translate("Dialog", "D"))
        self.prop_scaxis_marker.setItemText(9, _translate("Dialog", "d"))
        self.prop_scaxis_marker.setItemText(10, _translate("Dialog", "h"))
        self.prop_scaxis_marker.setItemText(11, _translate("Dialog", "H"))
        self.prop_scaxis_marker.setItemText(12, _translate("Dialog", "p"))
        self.prop_scaxis_marker.setItemText(13, _translate("Dialog", "|"))
        self.prop_scaxis_marker.setItemText(14, _translate("Dialog", "_"))
        self.prop_scaxis_marker.setItemText(15, _translate("Dialog", "*"))
        self.prop_scaxis_marker.setItemText(16, _translate("Dialog", "1"))
        self.prop_scaxis_marker.setItemText(17, _translate("Dialog", "2"))
        self.prop_scaxis_marker.setItemText(18, _translate("Dialog", "3"))
        self.prop_scaxis_marker.setItemText(19, _translate("Dialog", "4"))
        self.groupBox_2.setTitle(_translate("Dialog", "Small Circles"))
        self.label_4.setText(_translate("Dialog", "Symbol"))
        self.label_6.setText(_translate("Dialog", "Width"))
        self.label_5.setText(_translate("Dialog", "Color"))
        self.prop_sccirc_linestyles.setItemText(0, _translate("Dialog", "-"))
        self.prop_sccirc_linestyles.setItemText(1, _translate("Dialog", ":"))
        self.prop_sccirc_linestyles.setItemText(2, _translate("Dialog", "--"))
        self.prop_sccirc_linestyles.setItemText(3, _translate("Dialog", "-."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Projection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Statistics"))
        self.groupBox_17.setTitle(_translate("Dialog", "Small Circle Legend"))
        self.prop_checklegend_scaxis.setText(_translate("Dialog", "Axis"))
        self.prop_checklegend_sccirc.setText(_translate("Dialog", "Small Circle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Data Source"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.apply.setText(_translate("Dialog", "Apply"))

